#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include "rom/opi_flash.h"



#define DR_REG_EXTMEM_BASE                      0x600C4000
#define DR_REG_SPI0_BASE                        0x60003000
#define REG_SPI_MEM_BASE(i)     (DR_REG_SPI0_BASE - (i) * 0x1000)
#define SPI_MEM_SPI_SMEM_AC_REG(i)          (REG_SPI_MEM_BASE(i) + 0xDC)
#define EXTMEM_DCACHE_CTRL1_REG          (DR_REG_EXTMEM_BASE + 0x4)
#define PSRAM_MODE PSRAM_VADDR_MODE_NORMAL
#define EXTMEM_DCACHE_SHUT_CORE0_BUS    (1<<0)
#define EXTMEM_DCACHE_SHUT_CORE1_BUS    (1<<1)
#define SPI_MEM_CMD_REG(i)          (REG_SPI_MEM_BASE(i) + 0x0)
#define SPI_MEM_FLASH_READ    (1<<(31))
#define SPI_MEM_FLASH_READ_M  (1<<(31))
#define SPI_MEM_FLASH_READ_V  0x1
#define SPI_MEM_FLASH_READ_S  31
#define SPI_MEM_FLASH_WREN    (1<<(30))
#define SPI_MEM_FLASH_WREN_M  (1<<(30))
#define SPI_MEM_FLASH_WREN_V  0x1
#define SPI_MEM_FLASH_WREN_S  30
#define SPI_MEM_FLASH_WRDI    (1<<(29))
#define SPI_MEM_FLASH_WRDI_M  (1<<(29))
#define SPI_MEM_FLASH_WRDI_V  0x1
#define SPI_MEM_FLASH_WRDI_S  29
#define SPI_MEM_FLASH_RDID    (1<<(28))
#define SPI_MEM_FLASH_RDID_M  (1<<(28))
#define SPI_MEM_FLASH_RDID_V  0x1
#define SPI_MEM_FLASH_RDID_S  28
#define SPI_MEM_FLASH_RDSR    (1<<(27))
#define SPI_MEM_FLASH_RDSR_M  (1<<(27))
#define SPI_MEM_FLASH_RDSR_V  0x1
#define SPI_MEM_FLASH_RDSR_S  27
#define SPI_MEM_FLASH_WRSR    (1<<(26))
#define SPI_MEM_FLASH_WRSR_M  (1<<(26))
#define SPI_MEM_FLASH_WRSR_V  0x1
#define SPI_MEM_FLASH_WRSR_S  26
#define SPI_MEM_FLASH_PP    (1<<(25))
#define SPI_MEM_FLASH_PP_M  (1<<(25))
#define SPI_MEM_FLASH_PP_V  0x1
#define SPI_MEM_FLASH_PP_S  25
#define SPI_MEM_FLASH_SE    (1<<(24))
#define SPI_MEM_FLASH_SE_M  (1<<(24))
#define SPI_MEM_FLASH_SE_V  0x1
#define SPI_MEM_FLASH_SE_S  24
#define SPI_MEM_FLASH_BE    (1<<(23))
#define SPI_MEM_FLASH_BE_M  (1<<(23))
#define SPI_MEM_FLASH_BE_V  0x1
#define SPI_MEM_FLASH_BE_S  23
#define SPI_MEM_FLASH_CE    (1<<(22))
#define SPI_MEM_FLASH_CE_M  (1<<(22))
#define SPI_MEM_FLASH_CE_V  0x1
#define SPI_MEM_FLASH_CE_S  22
#define SPI_MEM_FLASH_DP    (1<<(21))
#define SPI_MEM_FLASH_DP_M  (1<<(21))
#define SPI_MEM_FLASH_DP_V  0x1
#define SPI_MEM_FLASH_DP_S  21
#define SPI_MEM_FLASH_RES    (1<<(20))
#define SPI_MEM_FLASH_RES_M  (1<<(20))
#define SPI_MEM_FLASH_RES_V  0x1
#define SPI_MEM_FLASH_RES_S  20
#define SPI_MEM_FLASH_HPM    (1<<(19))
#define SPI_MEM_FLASH_HPM_M  (1<<(19))
#define SPI_MEM_FLASH_HPM_V  0x1
#define SPI_MEM_FLASH_HPM_S  19
#define SPI_MEM_USR    (1<<(18))
#define SPI_MEM_USR_M  (1<<(18))
#define SPI_MEM_USR_V  0x1
#define SPI_MEM_USR_S  18
#define SPI_MEM_FLASH_PE    (1<<(17))
#define SPI_MEM_FLASH_PE_M  (1<<(17))
#define SPI_MEM_FLASH_PE_V  0x1
#define SPI_MEM_FLASH_PE_S  17
#define SPI_MEM_ADDR_REG(i)          (REG_SPI_MEM_BASE(i) + 0x4)
#define SPI_MEM_USR_ADDR_VALUE    0xFFFFFFFF
#define SPI_MEM_USR_ADDR_VALUE_M  ((SPI_MEM_USR_ADDR_VALUE_V)<<(SPI_MEM_USR_ADDR_VALUE_S))
#define SPI_MEM_USR_ADDR_VALUE_V  0xFFFFFFFF
#define SPI_MEM_USR_ADDR_VALUE_S  0
#define SPI_MEM_CTRL_REG(i)          (REG_SPI_MEM_BASE(i) + 0x8)
#define SPI_MEM_FREAD_QIO    (1<<(24))
#define SPI_MEM_FREAD_QIO_M  (1<<(24))
#define SPI_MEM_FREAD_QIO_V  0x1
#define SPI_MEM_FREAD_QIO_S  24
#define SPI_MEM_FREAD_DIO    (1<<(23))
#define SPI_MEM_FREAD_DIO_M  (1<<(23))
#define SPI_MEM_FREAD_DIO_V  0x1
#define SPI_MEM_FREAD_DIO_S  23
#define SPI_MEM_WRSR_2B    (1<<(22))
#define SPI_MEM_WRSR_2B_M  (1<<(22))
#define SPI_MEM_WRSR_2B_V  0x1
#define SPI_MEM_WRSR_2B_S  22
#define SPI_MEM_WP_REG    (1<<(21))
#define SPI_MEM_WP_REG_M  (1<<(21))
#define SPI_MEM_WP_REG_V  0x1
#define SPI_MEM_WP_REG_S  21
#define SPI_MEM_FREAD_QUAD    (1<<(20))
#define SPI_MEM_FREAD_QUAD_M  (1<<(20))
#define SPI_MEM_FREAD_QUAD_V  0x1
#define SPI_MEM_FREAD_QUAD_S  20
#define SPI_MEM_D_POL    (1<<(19))
#define SPI_MEM_D_POL_M  (1<<(19))
#define SPI_MEM_D_POL_V  0x1
#define SPI_MEM_D_POL_S  19
#define SPI_MEM_Q_POL    (1<<(18))
#define SPI_MEM_Q_POL_M  (1<<(18))
#define SPI_MEM_Q_POL_V  0x1
#define SPI_MEM_Q_POL_S  18
#define SPI_MEM_RESANDRES    (1<<(15))
#define SPI_MEM_RESANDRES_M  (1<<(15))
#define SPI_MEM_RESANDRES_V  0x1
#define SPI_MEM_RESANDRES_S  15
#define SPI_MEM_FREAD_DUAL    (1<<(14))
#define SPI_MEM_FREAD_DUAL_M  (1<<(14))
#define SPI_MEM_FREAD_DUAL_V  0x1
#define SPI_MEM_FREAD_DUAL_S  14
#define SPI_MEM_FASTRD_MODE    (1<<(13))
#define SPI_MEM_FASTRD_MODE_M  (1<<(13))
#define SPI_MEM_FASTRD_MODE_V  0x1
#define SPI_MEM_FASTRD_MODE_S  13
#define SPI_MEM_TX_CRC_EN    (1<<(11))
#define SPI_MEM_TX_CRC_EN_M  (1<<(11))
#define SPI_MEM_TX_CRC_EN_V  0x1
#define SPI_MEM_TX_CRC_EN_S  11
#define SPI_MEM_FCS_CRC_EN    (1<<(10))
#define SPI_MEM_FCS_CRC_EN_M  (1<<(10))
#define SPI_MEM_FCS_CRC_EN_V  0x1
#define SPI_MEM_FCS_CRC_EN_S  10
#define SPI_MEM_FCMD_OCT    (1<<(9))
#define SPI_MEM_FCMD_OCT_M  (1<<(9))
#define SPI_MEM_FCMD_OCT_V  0x1
#define SPI_MEM_FCMD_OCT_S  9
#define SPI_MEM_FCMD_QUAD    (1<<(8))
#define SPI_MEM_FCMD_QUAD_M  (1<<(8))
#define SPI_MEM_FCMD_QUAD_V  0x1
#define SPI_MEM_FCMD_QUAD_S  8
#define SPI_MEM_FCMD_DUAL    (1<<(7))
#define SPI_MEM_FCMD_DUAL_M  (1<<(7))
#define SPI_MEM_FCMD_DUAL_V  0x1
#define SPI_MEM_FCMD_DUAL_S  7
#define SPI_MEM_FADDR_OCT    (1<<(6))
#define SPI_MEM_FADDR_OCT_M  (1<<(6))
#define SPI_MEM_FADDR_OCT_V  0x1
#define SPI_MEM_FADDR_OCT_S  6
#define SPI_MEM_FDIN_OCT    (1<<(5))
#define SPI_MEM_FDIN_OCT_M  (1<<(5))
#define SPI_MEM_FDIN_OCT_V  0x1
#define SPI_MEM_FDIN_OCT_S  5
#define SPI_MEM_FDOUT_OCT    (1<<(4))
#define SPI_MEM_FDOUT_OCT_M  (1<<(4))
#define SPI_MEM_FDOUT_OCT_V  0x1
#define SPI_MEM_FDOUT_OCT_S  4
#define SPI_MEM_FDUMMY_OUT    (1<<(3))
#define SPI_MEM_FDUMMY_OUT_M  (1<<(3))
#define SPI_MEM_FDUMMY_OUT_V  0x1
#define SPI_MEM_FDUMMY_OUT_S  3
#define SPI_MEM_CTRL1_REG(i)          (REG_SPI_MEM_BASE(i) + 0xC)
#define SPI_MEM_RXFIFO_RST    (1<<(30))
#define SPI_MEM_RXFIFO_RST_M  (1<<(30))
#define SPI_MEM_RXFIFO_RST_V  0x1
#define SPI_MEM_RXFIFO_RST_S  30
#define SPI_MEM_CS_HOLD_DLY_RES    0x000003FF
#define SPI_MEM_CS_HOLD_DLY_RES_M  ((SPI_MEM_CS_HOLD_DLY_RES_V)<<(SPI_MEM_CS_HOLD_DLY_RES_S))
#define SPI_MEM_CS_HOLD_DLY_RES_V  0x3FF
#define SPI_MEM_CS_HOLD_DLY_RES_S  2
#define SPI_MEM_CLK_MODE    0x00000003
#define SPI_MEM_CLK_MODE_M  ((SPI_MEM_CLK_MODE_V)<<(SPI_MEM_CLK_MODE_S))
#define SPI_MEM_CLK_MODE_V  0x3
#define SPI_MEM_CLK_MODE_S  0
#define SPI_MEM_CTRL2_REG(i)          (REG_SPI_MEM_BASE(i) + 0x10)
#define SPI_MEM_SYNC_RESET    (1<<(31))
#define SPI_MEM_SYNC_RESET_M  (1<<(31))
#define SPI_MEM_SYNC_RESET_V  0x1
#define SPI_MEM_SYNC_RESET_S  31
#define SPI_MEM_CS_HOLD_DELAY    0x0000003F
#define SPI_MEM_CS_HOLD_DELAY_M  ((SPI_MEM_CS_HOLD_DELAY_V)<<(SPI_MEM_CS_HOLD_DELAY_S))
#define SPI_MEM_CS_HOLD_DELAY_V  0x3F
#define SPI_MEM_CS_HOLD_DELAY_S  25
#define SPI_MEM_ECC_16TO18_BYTE_EN    (1<<(14))
#define SPI_MEM_ECC_16TO18_BYTE_EN_M  (1<<(14))
#define SPI_MEM_ECC_16TO18_BYTE_EN_V  0x1
#define SPI_MEM_ECC_16TO18_BYTE_EN_S  14
#define SPI_MEM_ECC_SKIP_PAGE_CORNER    (1<<(13))
#define SPI_MEM_ECC_SKIP_PAGE_CORNER_M  (1<<(13))
#define SPI_MEM_ECC_SKIP_PAGE_CORNER_V  0x1
#define SPI_MEM_ECC_SKIP_PAGE_CORNER_S  13
#define SPI_MEM_ECC_CS_HOLD_TIME    0x00000007
#define SPI_MEM_ECC_CS_HOLD_TIME_M  ((SPI_MEM_ECC_CS_HOLD_TIME_V)<<(SPI_MEM_ECC_CS_HOLD_TIME_S))
#define SPI_MEM_ECC_CS_HOLD_TIME_V  0x7
#define SPI_MEM_ECC_CS_HOLD_TIME_S  10
#define SPI_MEM_CS_HOLD_TIME    0x0000001F
#define SPI_MEM_CS_HOLD_TIME_M  ((SPI_MEM_CS_HOLD_TIME_V)<<(SPI_MEM_CS_HOLD_TIME_S))
#define SPI_MEM_CS_HOLD_TIME_V  0x1F
#define SPI_MEM_CS_HOLD_TIME_S  5
#define SPI_MEM_CS_SETUP_TIME    0x0000001F
#define SPI_MEM_CS_SETUP_TIME_M  ((SPI_MEM_CS_SETUP_TIME_V)<<(SPI_MEM_CS_SETUP_TIME_S))
#define SPI_MEM_CS_SETUP_TIME_V  0x1F
#define SPI_MEM_CS_SETUP_TIME_S  0
#define SPI_MEM_CLOCK_REG(i)          (REG_SPI_MEM_BASE(i) + 0x14)
#define SPI_MEM_CLK_EQU_SYSCLK    (1<<(31))
#define SPI_MEM_CLK_EQU_SYSCLK_M  (1<<(31))
#define SPI_MEM_CLK_EQU_SYSCLK_V  0x1
#define SPI_MEM_CLK_EQU_SYSCLK_S  31
#define SPI_MEM_CLKCNT_N    0x000000FF
#define SPI_MEM_CLKCNT_N_M  ((SPI_MEM_CLKCNT_N_V)<<(SPI_MEM_CLKCNT_N_S))
#define SPI_MEM_CLKCNT_N_V  0xFF
#define SPI_MEM_CLKCNT_N_S  16
#define SPI_MEM_CLKCNT_H    0x000000FF
#define SPI_MEM_CLKCNT_H_M  ((SPI_MEM_CLKCNT_H_V)<<(SPI_MEM_CLKCNT_H_S))
#define SPI_MEM_CLKCNT_H_V  0xFF
#define SPI_MEM_CLKCNT_H_S  8
#define SPI_MEM_CLKCNT_L    0x000000FF
#define SPI_MEM_CLKCNT_L_M  ((SPI_MEM_CLKCNT_L_V)<<(SPI_MEM_CLKCNT_L_S))
#define SPI_MEM_CLKCNT_L_V  0xFF
#define SPI_MEM_CLKCNT_L_S  0
#define SPI_MEM_USER_REG(i)          (REG_SPI_MEM_BASE(i) + 0x18)
#define SPI_MEM_USR_COMMAND    (1<<(31))
#define SPI_MEM_USR_COMMAND_M  (1<<(31))
#define SPI_MEM_USR_COMMAND_V  0x1
#define SPI_MEM_USR_COMMAND_S  31
#define SPI_MEM_USR_ADDR    (1<<(30))
#define SPI_MEM_USR_ADDR_M  (1<<(30))
#define SPI_MEM_USR_ADDR_V  0x1
#define SPI_MEM_USR_ADDR_S  30
#define SPI_MEM_USR_DUMMY    (1<<(29))
#define SPI_MEM_USR_DUMMY_M  (1<<(29))
#define SPI_MEM_USR_DUMMY_V  0x1
#define SPI_MEM_USR_DUMMY_S  29
#define SPI_MEM_USR_MISO    (1<<(28))
#define SPI_MEM_USR_MISO_M  (1<<(28))
#define SPI_MEM_USR_MISO_V  0x1
#define SPI_MEM_USR_MISO_S  28
#define SPI_MEM_USR_MOSI    (1<<(27))
#define SPI_MEM_USR_MOSI_M  (1<<(27))
#define SPI_MEM_USR_MOSI_V  0x1
#define SPI_MEM_USR_MOSI_S  27
#define SPI_MEM_USR_DUMMY_IDLE    (1<<(26))
#define SPI_MEM_USR_DUMMY_IDLE_M  (1<<(26))
#define SPI_MEM_USR_DUMMY_IDLE_V  0x1
#define SPI_MEM_USR_DUMMY_IDLE_S  26
#define SPI_MEM_USR_MOSI_HIGHPART    (1<<(25))
#define SPI_MEM_USR_MOSI_HIGHPART_M  (1<<(25))
#define SPI_MEM_USR_MOSI_HIGHPART_V  0x1
#define SPI_MEM_USR_MOSI_HIGHPART_S  25
#define SPI_MEM_USR_MISO_HIGHPART    (1<<(24))
#define SPI_MEM_USR_MISO_HIGHPART_M  (1<<(24))
#define SPI_MEM_USR_MISO_HIGHPART_V  0x1
#define SPI_MEM_USR_MISO_HIGHPART_S  24
#define SPI_MEM_FWRITE_QIO    (1<<(15))
#define SPI_MEM_FWRITE_QIO_M  (1<<(15))
#define SPI_MEM_FWRITE_QIO_V  0x1
#define SPI_MEM_FWRITE_QIO_S  15
#define SPI_MEM_FWRITE_DIO    (1<<(14))
#define SPI_MEM_FWRITE_DIO_M  (1<<(14))
#define SPI_MEM_FWRITE_DIO_V  0x1
#define SPI_MEM_FWRITE_DIO_S  14
#define SPI_MEM_FWRITE_QUAD    (1<<(13))
#define SPI_MEM_FWRITE_QUAD_M  (1<<(13))
#define SPI_MEM_FWRITE_QUAD_V  0x1
#define SPI_MEM_FWRITE_QUAD_S  13
#define SPI_MEM_FWRITE_DUAL    (1<<(12))
#define SPI_MEM_FWRITE_DUAL_M  (1<<(12))
#define SPI_MEM_FWRITE_DUAL_V  0x1
#define SPI_MEM_FWRITE_DUAL_S  12
#define SPI_MEM_CK_OUT_EDGE    (1<<(9))
#define SPI_MEM_CK_OUT_EDGE_M  (1<<(9))
#define SPI_MEM_CK_OUT_EDGE_V  0x1
#define SPI_MEM_CK_OUT_EDGE_S  9
#define SPI_MEM_CS_SETUP    (1<<(7))
#define SPI_MEM_CS_SETUP_M  (1<<(7))
#define SPI_MEM_CS_SETUP_V  0x1
#define SPI_MEM_CS_SETUP_S  7
#define SPI_MEM_CS_HOLD    (1<<(6))
#define SPI_MEM_CS_HOLD_M  (1<<(6))
#define SPI_MEM_CS_HOLD_V  0x1
#define SPI_MEM_CS_HOLD_S  6
#define SPI_MEM_USER1_REG(i)          (REG_SPI_MEM_BASE(i) + 0x1C)
#define SPI_MEM_USR_ADDR_BITLEN    0x0000003F
#define SPI_MEM_USR_ADDR_BITLEN_M  ((SPI_MEM_USR_ADDR_BITLEN_V)<<(SPI_MEM_USR_ADDR_BITLEN_S))
#define SPI_MEM_USR_ADDR_BITLEN_V  0x3F
#define SPI_MEM_USR_ADDR_BITLEN_S  26
#define SPI_MEM_USR_DUMMY_CYCLELEN    0x0000003F
#define SPI_MEM_USR_DUMMY_CYCLELEN_M  ((SPI_MEM_USR_DUMMY_CYCLELEN_V)<<(SPI_MEM_USR_DUMMY_CYCLELEN_S))
#define SPI_MEM_USR_DUMMY_CYCLELEN_V  0x3F
#define SPI_MEM_USR_DUMMY_CYCLELEN_S  0
#define SPI_MEM_USER2_REG(i)          (REG_SPI_MEM_BASE(i) + 0x20)
#define SPI_MEM_USR_COMMAND_BITLEN    0x0000000F
#define SPI_MEM_USR_COMMAND_BITLEN_M  ((SPI_MEM_USR_COMMAND_BITLEN_V)<<(SPI_MEM_USR_COMMAND_BITLEN_S))
#define SPI_MEM_USR_COMMAND_BITLEN_V  0xF
#define SPI_MEM_USR_COMMAND_BITLEN_S  28
#define SPI_MEM_USR_COMMAND_VALUE    0x0000FFFF
#define SPI_MEM_USR_COMMAND_VALUE_M  ((SPI_MEM_USR_COMMAND_VALUE_V)<<(SPI_MEM_USR_COMMAND_VALUE_S))
#define SPI_MEM_USR_COMMAND_VALUE_V  0xFFFF
#define SPI_MEM_USR_COMMAND_VALUE_S  0
#define SPI_MEM_MOSI_DLEN_REG(i)          (REG_SPI_MEM_BASE(i) + 0x24)
#define SPI_MEM_USR_MOSI_DBITLEN    0x000003FF
#define SPI_MEM_USR_MOSI_DBITLEN_M  ((SPI_MEM_USR_MOSI_DBITLEN_V)<<(SPI_MEM_USR_MOSI_DBITLEN_S))
#define SPI_MEM_USR_MOSI_DBITLEN_V  0x3FF
#define SPI_MEM_USR_MOSI_DBITLEN_S  0
#define SPI_MEM_MISO_DLEN_REG(i)          (REG_SPI_MEM_BASE(i) + 0x28)
#define SPI_MEM_USR_MISO_DBITLEN    0x000003FF
#define SPI_MEM_USR_MISO_DBITLEN_M  ((SPI_MEM_USR_MISO_DBITLEN_V)<<(SPI_MEM_USR_MISO_DBITLEN_S))
#define SPI_MEM_USR_MISO_DBITLEN_V  0x3FF
#define SPI_MEM_USR_MISO_DBITLEN_S  0
#define SPI_MEM_RD_STATUS_REG(i)          (REG_SPI_MEM_BASE(i) + 0x2C)
#define SPI_MEM_WB_MODE    0x000000FF
#define SPI_MEM_WB_MODE_M  ((SPI_MEM_WB_MODE_V)<<(SPI_MEM_WB_MODE_S))
#define SPI_MEM_WB_MODE_V  0xFF
#define SPI_MEM_WB_MODE_S  16
#define SPI_MEM_STATUS    0x0000FFFF
#define SPI_MEM_STATUS_M  ((SPI_MEM_STATUS_V)<<(SPI_MEM_STATUS_S))
#define SPI_MEM_STATUS_V  0xFFFF
#define SPI_MEM_STATUS_S  0
#define SPI_MEM_EXT_ADDR_REG(i)          (REG_SPI_MEM_BASE(i) + 0x30)
#define SPI_MEM_EXT_ADDR    0xFFFFFFFF
#define SPI_MEM_EXT_ADDR_M  ((SPI_MEM_EXT_ADDR_V)<<(SPI_MEM_EXT_ADDR_S))
#define SPI_MEM_EXT_ADDR_V  0xFFFFFFFF
#define SPI_MEM_EXT_ADDR_S  0
#define SPI_MEM_MISC_REG(i)          (REG_SPI_MEM_BASE(i) + 0x34)
#define SPI_MEM_AUTO_PER    (1<<(11))
#define SPI_MEM_AUTO_PER_M  (1<<(11))
#define SPI_MEM_AUTO_PER_V  0x1
#define SPI_MEM_AUTO_PER_S  11
#define SPI_MEM_CS_KEEP_ACTIVE    (1<<(10))
#define SPI_MEM_CS_KEEP_ACTIVE_M  (1<<(10))
#define SPI_MEM_CS_KEEP_ACTIVE_V  0x1
#define SPI_MEM_CS_KEEP_ACTIVE_S  10
#define SPI_MEM_CK_IDLE_EDGE    (1<<(9))
#define SPI_MEM_CK_IDLE_EDGE_M  (1<<(9))
#define SPI_MEM_CK_IDLE_EDGE_V  0x1
#define SPI_MEM_CK_IDLE_EDGE_S  9
#define SPI_MEM_SSUB_PIN    (1<<(8))
#define SPI_MEM_SSUB_PIN_M  (1<<(8))
#define SPI_MEM_SSUB_PIN_V  0x1
#define SPI_MEM_SSUB_PIN_S  8
#define SPI_MEM_FSUB_PIN    (1<<(7))
#define SPI_MEM_FSUB_PIN_M  (1<<(7))
#define SPI_MEM_FSUB_PIN_V  0x1
#define SPI_MEM_FSUB_PIN_S  7
#define SPI_MEM_CS1_DIS    (1<<(1))
#define SPI_MEM_CS1_DIS_M  (1<<(1))
#define SPI_MEM_CS1_DIS_V  0x1
#define SPI_MEM_CS1_DIS_S  1
#define SPI_MEM_CS0_DIS    (1<<(0))
#define SPI_MEM_CS0_DIS_M  (1<<(0))
#define SPI_MEM_CS0_DIS_V  0x1
#define SPI_MEM_CS0_DIS_S  0
#define SPI_MEM_TX_CRC_REG(i)          (REG_SPI_MEM_BASE(i) + 0x38)
#define SPI_MEM_TX_CRC_DATA    0xFFFFFFFF
#define SPI_MEM_TX_CRC_DATA_M  ((SPI_MEM_TX_CRC_DATA_V)<<(SPI_MEM_TX_CRC_DATA_S))
#define SPI_MEM_TX_CRC_DATA_V  0xFFFFFFFF
#define SPI_MEM_TX_CRC_DATA_S  0
#define SPI_MEM_CACHE_FCTRL_REG(i)          (REG_SPI_MEM_BASE(i) + 0x3C)
#define SPI_MEM_FADDR_QUAD    (1<<(8))
#define SPI_MEM_FADDR_QUAD_M  (1<<(8))
#define SPI_MEM_FADDR_QUAD_V  0x1
#define SPI_MEM_FADDR_QUAD_S  8
#define SPI_MEM_FDOUT_QUAD    (1<<(7))
#define SPI_MEM_FDOUT_QUAD_M  (1<<(7))
#define SPI_MEM_FDOUT_QUAD_V  0x1
#define SPI_MEM_FDOUT_QUAD_S  7
#define SPI_MEM_FDIN_QUAD    (1<<(6))
#define SPI_MEM_FDIN_QUAD_M  (1<<(6))
#define SPI_MEM_FDIN_QUAD_V  0x1
#define SPI_MEM_FDIN_QUAD_S  6
#define SPI_MEM_FADDR_DUAL    (1<<(5))
#define SPI_MEM_FADDR_DUAL_M  (1<<(5))
#define SPI_MEM_FADDR_DUAL_V  0x1
#define SPI_MEM_FADDR_DUAL_S  5
#define SPI_MEM_FDOUT_DUAL    (1<<(4))
#define SPI_MEM_FDOUT_DUAL_M  (1<<(4))
#define SPI_MEM_FDOUT_DUAL_V  0x1
#define SPI_MEM_FDOUT_DUAL_S  4
#define SPI_MEM_FDIN_DUAL    (1<<(3))
#define SPI_MEM_FDIN_DUAL_M  (1<<(3))
#define SPI_MEM_FDIN_DUAL_V  0x1
#define SPI_MEM_FDIN_DUAL_S  3
#define SPI_MEM_CACHE_FLASH_USR_CMD    (1<<(2))
#define SPI_MEM_CACHE_FLASH_USR_CMD_M  (1<<(2))
#define SPI_MEM_CACHE_FLASH_USR_CMD_V  0x1
#define SPI_MEM_CACHE_FLASH_USR_CMD_S  2
#define SPI_MEM_CACHE_USR_CMD_4BYTE    (1<<(1))
#define SPI_MEM_CACHE_USR_CMD_4BYTE_M  (1<<(1))
#define SPI_MEM_CACHE_USR_CMD_4BYTE_V  0x1
#define SPI_MEM_CACHE_USR_CMD_4BYTE_S  1
#define SPI_MEM_CACHE_REQ_EN    (1<<(0))
#define SPI_MEM_CACHE_REQ_EN_M  (1<<(0))
#define SPI_MEM_CACHE_REQ_EN_V  0x1
#define SPI_MEM_CACHE_REQ_EN_S  0
#define SPI_MEM_CACHE_SCTRL_REG(i)          (REG_SPI_MEM_BASE(i) + 0x40)
#define SPI_MEM_SRAM_WDUMMY_CYCLELEN    0x0000003F
#define SPI_MEM_SRAM_WDUMMY_CYCLELEN_M  ((SPI_MEM_SRAM_WDUMMY_CYCLELEN_V)<<(SPI_MEM_SRAM_WDUMMY_CYCLELEN_S))
#define SPI_MEM_SRAM_WDUMMY_CYCLELEN_V  0x3F
#define SPI_MEM_SRAM_WDUMMY_CYCLELEN_S  22
#define SPI_MEM_SRAM_OCT    (1<<(21))
#define SPI_MEM_SRAM_OCT_M  (1<<(21))
#define SPI_MEM_SRAM_OCT_V  0x1
#define SPI_MEM_SRAM_OCT_S  21
#define SPI_MEM_CACHE_SRAM_USR_WCMD    (1<<(20))
#define SPI_MEM_CACHE_SRAM_USR_WCMD_M  (1<<(20))
#define SPI_MEM_CACHE_SRAM_USR_WCMD_V  0x1
#define SPI_MEM_CACHE_SRAM_USR_WCMD_S  20
#define SPI_MEM_SRAM_ADDR_BITLEN    0x0000003F
#define SPI_MEM_SRAM_ADDR_BITLEN_M  ((SPI_MEM_SRAM_ADDR_BITLEN_V)<<(SPI_MEM_SRAM_ADDR_BITLEN_S))
#define SPI_MEM_SRAM_ADDR_BITLEN_V  0x3F
#define SPI_MEM_SRAM_ADDR_BITLEN_S  14
#define SPI_MEM_SRAM_RDUMMY_CYCLELEN    0x0000003F
#define SPI_MEM_SRAM_RDUMMY_CYCLELEN_M  ((SPI_MEM_SRAM_RDUMMY_CYCLELEN_V)<<(SPI_MEM_SRAM_RDUMMY_CYCLELEN_S))
#define SPI_MEM_SRAM_RDUMMY_CYCLELEN_V  0x3F
#define SPI_MEM_SRAM_RDUMMY_CYCLELEN_S  6
#define SPI_MEM_CACHE_SRAM_USR_RCMD    (1<<(5))
#define SPI_MEM_CACHE_SRAM_USR_RCMD_M  (1<<(5))
#define SPI_MEM_CACHE_SRAM_USR_RCMD_V  0x1
#define SPI_MEM_CACHE_SRAM_USR_RCMD_S  5
#define SPI_MEM_USR_RD_SRAM_DUMMY    (1<<(4))
#define SPI_MEM_USR_RD_SRAM_DUMMY_M  (1<<(4))
#define SPI_MEM_USR_RD_SRAM_DUMMY_V  0x1
#define SPI_MEM_USR_RD_SRAM_DUMMY_S  4
#define SPI_MEM_USR_WR_SRAM_DUMMY    (1<<(3))
#define SPI_MEM_USR_WR_SRAM_DUMMY_M  (1<<(3))
#define SPI_MEM_USR_WR_SRAM_DUMMY_V  0x1
#define SPI_MEM_USR_WR_SRAM_DUMMY_S  3
#define SPI_MEM_USR_SRAM_QIO    (1<<(2))
#define SPI_MEM_USR_SRAM_QIO_M  (1<<(2))
#define SPI_MEM_USR_SRAM_QIO_V  0x1
#define SPI_MEM_USR_SRAM_QIO_S  2
#define SPI_MEM_USR_SRAM_DIO    (1<<(1))
#define SPI_MEM_USR_SRAM_DIO_M  (1<<(1))
#define SPI_MEM_USR_SRAM_DIO_V  0x1
#define SPI_MEM_USR_SRAM_DIO_S  1
#define SPI_MEM_CACHE_USR_SCMD_4BYTE    (1<<(0))
#define SPI_MEM_CACHE_USR_SCMD_4BYTE_M  (1<<(0))
#define SPI_MEM_CACHE_USR_SCMD_4BYTE_V  0x1
#define SPI_MEM_CACHE_USR_SCMD_4BYTE_S  0
#define SPI_MEM_SRAM_CMD_REG(i)          (REG_SPI_MEM_BASE(i) + 0x44)
#define SPI_MEM_SDUMMY_OUT    (1<<(22))
#define SPI_MEM_SDUMMY_OUT_M  (1<<(22))
#define SPI_MEM_SDUMMY_OUT_V  0x1
#define SPI_MEM_SDUMMY_OUT_S  22
#define SPI_MEM_SCMD_OCT    (1<<(21))
#define SPI_MEM_SCMD_OCT_M  (1<<(21))
#define SPI_MEM_SCMD_OCT_V  0x1
#define SPI_MEM_SCMD_OCT_S  21
#define SPI_MEM_SADDR_OCT    (1<<(20))
#define SPI_MEM_SADDR_OCT_M  (1<<(20))
#define SPI_MEM_SADDR_OCT_V  0x1
#define SPI_MEM_SADDR_OCT_S  20
#define SPI_MEM_SDOUT_OCT    (1<<(19))
#define SPI_MEM_SDOUT_OCT_M  (1<<(19))
#define SPI_MEM_SDOUT_OCT_V  0x1
#define SPI_MEM_SDOUT_OCT_S  19
#define SPI_MEM_SDIN_OCT    (1<<(18))
#define SPI_MEM_SDIN_OCT_M  (1<<(18))
#define SPI_MEM_SDIN_OCT_V  0x1
#define SPI_MEM_SDIN_OCT_S  18
#define SPI_MEM_SCMD_QUAD    (1<<(17))
#define SPI_MEM_SCMD_QUAD_M  (1<<(17))
#define SPI_MEM_SCMD_QUAD_V  0x1
#define SPI_MEM_SCMD_QUAD_S  17
#define SPI_MEM_SADDR_QUAD    (1<<(16))
#define SPI_MEM_SADDR_QUAD_M  (1<<(16))
#define SPI_MEM_SADDR_QUAD_V  0x1
#define SPI_MEM_SADDR_QUAD_S  16
#define SPI_MEM_SDOUT_QUAD    (1<<(15))
#define SPI_MEM_SDOUT_QUAD_M  (1<<(15))
#define SPI_MEM_SDOUT_QUAD_V  0x1
#define SPI_MEM_SDOUT_QUAD_S  15
#define SPI_MEM_SDIN_QUAD    (1<<(14))
#define SPI_MEM_SDIN_QUAD_M  (1<<(14))
#define SPI_MEM_SDIN_QUAD_V  0x1
#define SPI_MEM_SDIN_QUAD_S  14
#define SPI_MEM_SCMD_DUAL    (1<<(13))
#define SPI_MEM_SCMD_DUAL_M  (1<<(13))
#define SPI_MEM_SCMD_DUAL_V  0x1
#define SPI_MEM_SCMD_DUAL_S  13
#define SPI_MEM_SADDR_DUAL    (1<<(12))
#define SPI_MEM_SADDR_DUAL_M  (1<<(12))
#define SPI_MEM_SADDR_DUAL_V  0x1
#define SPI_MEM_SADDR_DUAL_S  12
#define SPI_MEM_SDOUT_DUAL    (1<<(11))
#define SPI_MEM_SDOUT_DUAL_M  (1<<(11))
#define SPI_MEM_SDOUT_DUAL_V  0x1
#define SPI_MEM_SDOUT_DUAL_S  11
#define SPI_MEM_SDIN_DUAL    (1<<(10))
#define SPI_MEM_SDIN_DUAL_M  (1<<(10))
#define SPI_MEM_SDIN_DUAL_V  0x1
#define SPI_MEM_SDIN_DUAL_S  10
#define SPI_MEM_SWB_MODE    0x000000FF
#define SPI_MEM_SWB_MODE_M  ((SPI_MEM_SWB_MODE_V)<<(SPI_MEM_SWB_MODE_S))
#define SPI_MEM_SWB_MODE_V  0xFF
#define SPI_MEM_SWB_MODE_S  2
#define SPI_MEM_SCLK_MODE    0x00000003
#define SPI_MEM_SCLK_MODE_M  ((SPI_MEM_SCLK_MODE_V)<<(SPI_MEM_SCLK_MODE_S))
#define SPI_MEM_SCLK_MODE_V  0x3
#define SPI_MEM_SCLK_MODE_S  0
#define SPI_MEM_SRAM_DRD_CMD_REG(i)          (REG_SPI_MEM_BASE(i) + 0x48)
#define SPI_MEM_CACHE_SRAM_USR_RD_CMD_BITLEN    0x0000000F
#define SPI_MEM_CACHE_SRAM_USR_RD_CMD_BITLEN_M  ((SPI_MEM_CACHE_SRAM_USR_RD_CMD_BITLEN_V)<<(SPI_MEM_CACHE_SRAM_USR_RD_CMD_BITLEN_S))
#define SPI_MEM_CACHE_SRAM_USR_RD_CMD_BITLEN_V  0xF
#define SPI_MEM_CACHE_SRAM_USR_RD_CMD_BITLEN_S  28
#define SPI_MEM_CACHE_SRAM_USR_RD_CMD_VALUE    0x0000FFFF
#define SPI_MEM_CACHE_SRAM_USR_RD_CMD_VALUE_M  ((SPI_MEM_CACHE_SRAM_USR_RD_CMD_VALUE_V)<<(SPI_MEM_CACHE_SRAM_USR_RD_CMD_VALUE_S))
#define SPI_MEM_CACHE_SRAM_USR_RD_CMD_VALUE_V  0xFFFF
#define SPI_MEM_CACHE_SRAM_USR_RD_CMD_VALUE_S  0
#define SPI_MEM_SRAM_DWR_CMD_REG(i)          (REG_SPI_MEM_BASE(i) + 0x4C)
#define SPI_MEM_CACHE_SRAM_USR_WR_CMD_BITLEN    0x0000000F
#define SPI_MEM_CACHE_SRAM_USR_WR_CMD_BITLEN_M  ((SPI_MEM_CACHE_SRAM_USR_WR_CMD_BITLEN_V)<<(SPI_MEM_CACHE_SRAM_USR_WR_CMD_BITLEN_S))
#define SPI_MEM_CACHE_SRAM_USR_WR_CMD_BITLEN_V  0xF
#define SPI_MEM_CACHE_SRAM_USR_WR_CMD_BITLEN_S  28
#define SPI_MEM_CACHE_SRAM_USR_WR_CMD_VALUE    0x0000FFFF
#define SPI_MEM_CACHE_SRAM_USR_WR_CMD_VALUE_M  ((SPI_MEM_CACHE_SRAM_USR_WR_CMD_VALUE_V)<<(SPI_MEM_CACHE_SRAM_USR_WR_CMD_VALUE_S))
#define SPI_MEM_CACHE_SRAM_USR_WR_CMD_VALUE_V  0xFFFF
#define SPI_MEM_CACHE_SRAM_USR_WR_CMD_VALUE_S  0
#define SPI_MEM_SRAM_CLK_REG(i)          (REG_SPI_MEM_BASE(i) + 0x50)
#define SPI_MEM_SCLK_EQU_SYSCLK    (1<<(31))
#define SPI_MEM_SCLK_EQU_SYSCLK_M  (1<<(31))
#define SPI_MEM_SCLK_EQU_SYSCLK_V  0x1
#define SPI_MEM_SCLK_EQU_SYSCLK_S  31
#define SPI_MEM_SCLKCNT_N    0x000000FF
#define SPI_MEM_SCLKCNT_N_M  ((SPI_MEM_SCLKCNT_N_V)<<(SPI_MEM_SCLKCNT_N_S))
#define SPI_MEM_SCLKCNT_N_V  0xFF
#define SPI_MEM_SCLKCNT_N_S  16
#define SPI_MEM_SCLKCNT_H    0x000000FF
#define SPI_MEM_SCLKCNT_H_M  ((SPI_MEM_SCLKCNT_H_V)<<(SPI_MEM_SCLKCNT_H_S))
#define SPI_MEM_SCLKCNT_H_V  0xFF
#define SPI_MEM_SCLKCNT_H_S  8
#define SPI_MEM_SCLKCNT_L    0x000000FF
#define SPI_MEM_SCLKCNT_L_M  ((SPI_MEM_SCLKCNT_L_V)<<(SPI_MEM_SCLKCNT_L_S))
#define SPI_MEM_SCLKCNT_L_V  0xFF
#define SPI_MEM_SCLKCNT_L_S  0
#define SPI_MEM_FSM_REG(i)          (REG_SPI_MEM_BASE(i) + 0x54)
#define SPI_MEM_ST    0x00000007
#define SPI_MEM_ST_M  ((SPI_MEM_ST_V)<<(SPI_MEM_ST_S))
#define SPI_MEM_ST_V  0x7
#define SPI_MEM_ST_S  0
#define SPI_MEM_W0_REG(i)          (REG_SPI_MEM_BASE(i) + 0x58)
#define SPI_MEM_BUF0    0xFFFFFFFF
#define SPI_MEM_BUF0_M  ((SPI_MEM_BUF0_V)<<(SPI_MEM_BUF0_S))
#define SPI_MEM_BUF0_V  0xFFFFFFFF
#define SPI_MEM_BUF0_S  0
#define SPI_MEM_W1_REG(i)          (REG_SPI_MEM_BASE(i) + 0x5C)
#define SPI_MEM_BUF1    0xFFFFFFFF
#define SPI_MEM_BUF1_M  ((SPI_MEM_BUF1_V)<<(SPI_MEM_BUF1_S))
#define SPI_MEM_BUF1_V  0xFFFFFFFF
#define SPI_MEM_BUF1_S  0
#define SPI_MEM_W2_REG(i)          (REG_SPI_MEM_BASE(i) + 0x60)
#define SPI_MEM_BUF2    0xFFFFFFFF
#define SPI_MEM_BUF2_M  ((SPI_MEM_BUF2_V)<<(SPI_MEM_BUF2_S))
#define SPI_MEM_BUF2_V  0xFFFFFFFF
#define SPI_MEM_BUF2_S  0
#define SPI_MEM_W3_REG(i)          (REG_SPI_MEM_BASE(i) + 0x64)
#define SPI_MEM_BUF3    0xFFFFFFFF
#define SPI_MEM_BUF3_M  ((SPI_MEM_BUF3_V)<<(SPI_MEM_BUF3_S))
#define SPI_MEM_BUF3_V  0xFFFFFFFF
#define SPI_MEM_BUF3_S  0
#define SPI_MEM_W4_REG(i)          (REG_SPI_MEM_BASE(i) + 0x68)
#define SPI_MEM_BUF4    0xFFFFFFFF
#define SPI_MEM_BUF4_M  ((SPI_MEM_BUF4_V)<<(SPI_MEM_BUF4_S))
#define SPI_MEM_BUF4_V  0xFFFFFFFF
#define SPI_MEM_BUF4_S  0
#define SPI_MEM_W5_REG(i)          (REG_SPI_MEM_BASE(i) + 0x6C)
#define SPI_MEM_BUF5    0xFFFFFFFF
#define SPI_MEM_BUF5_M  ((SPI_MEM_BUF5_V)<<(SPI_MEM_BUF5_S))
#define SPI_MEM_BUF5_V  0xFFFFFFFF
#define SPI_MEM_BUF5_S  0
#define SPI_MEM_W6_REG(i)          (REG_SPI_MEM_BASE(i) + 0x70)
#define SPI_MEM_BUF6    0xFFFFFFFF
#define SPI_MEM_BUF6_M  ((SPI_MEM_BUF6_V)<<(SPI_MEM_BUF6_S))
#define SPI_MEM_BUF6_V  0xFFFFFFFF
#define SPI_MEM_BUF6_S  0
#define SPI_MEM_W7_REG(i)          (REG_SPI_MEM_BASE(i) + 0x74)
#define SPI_MEM_BUF7    0xFFFFFFFF
#define SPI_MEM_BUF7_M  ((SPI_MEM_BUF7_V)<<(SPI_MEM_BUF7_S))
#define SPI_MEM_BUF7_V  0xFFFFFFFF
#define SPI_MEM_BUF7_S  0
#define SPI_MEM_W8_REG(i)          (REG_SPI_MEM_BASE(i) + 0x78)
#define SPI_MEM_BUF8    0xFFFFFFFF
#define SPI_MEM_BUF8_M  ((SPI_MEM_BUF8_V)<<(SPI_MEM_BUF8_S))
#define SPI_MEM_BUF8_V  0xFFFFFFFF
#define SPI_MEM_BUF8_S  0
#define SPI_MEM_W9_REG(i)          (REG_SPI_MEM_BASE(i) + 0x7C)
#define SPI_MEM_BUF9    0xFFFFFFFF
#define SPI_MEM_BUF9_M  ((SPI_MEM_BUF9_V)<<(SPI_MEM_BUF9_S))
#define SPI_MEM_BUF9_V  0xFFFFFFFF
#define SPI_MEM_BUF9_S  0
#define SPI_MEM_W10_REG(i)          (REG_SPI_MEM_BASE(i) + 0x80)
#define SPI_MEM_BUF10    0xFFFFFFFF
#define SPI_MEM_BUF10_M  ((SPI_MEM_BUF10_V)<<(SPI_MEM_BUF10_S))
#define SPI_MEM_BUF10_V  0xFFFFFFFF
#define SPI_MEM_BUF10_S  0
#define SPI_MEM_W11_REG(i)          (REG_SPI_MEM_BASE(i) + 0x84)
#define SPI_MEM_BUF11    0xFFFFFFFF
#define SPI_MEM_BUF11_M  ((SPI_MEM_BUF11_V)<<(SPI_MEM_BUF11_S))
#define SPI_MEM_BUF11_V  0xFFFFFFFF
#define SPI_MEM_BUF11_S  0
#define SPI_MEM_W12_REG(i)          (REG_SPI_MEM_BASE(i) + 0x88)
#define SPI_MEM_BUF12    0xFFFFFFFF
#define SPI_MEM_BUF12_M  ((SPI_MEM_BUF12_V)<<(SPI_MEM_BUF12_S))
#define SPI_MEM_BUF12_V  0xFFFFFFFF
#define SPI_MEM_BUF12_S  0
#define SPI_MEM_W13_REG(i)          (REG_SPI_MEM_BASE(i) + 0x8C)
#define SPI_MEM_BUF13    0xFFFFFFFF
#define SPI_MEM_BUF13_M  ((SPI_MEM_BUF13_V)<<(SPI_MEM_BUF13_S))
#define SPI_MEM_BUF13_V  0xFFFFFFFF
#define SPI_MEM_BUF13_S  0
#define SPI_MEM_W14_REG(i)          (REG_SPI_MEM_BASE(i) + 0x90)
#define SPI_MEM_BUF14    0xFFFFFFFF
#define SPI_MEM_BUF14_M  ((SPI_MEM_BUF14_V)<<(SPI_MEM_BUF14_S))
#define SPI_MEM_BUF14_V  0xFFFFFFFF
#define SPI_MEM_BUF14_S  0
#define SPI_MEM_W15_REG(i)          (REG_SPI_MEM_BASE(i) + 0x94)
#define SPI_MEM_BUF15    0xFFFFFFFF
#define SPI_MEM_BUF15_M  ((SPI_MEM_BUF15_V)<<(SPI_MEM_BUF15_S))
#define SPI_MEM_BUF15_V  0xFFFFFFFF
#define SPI_MEM_BUF15_S  0
#define SPI_MEM_FLASH_WAITI_CTRL_REG(i)          (REG_SPI_MEM_BASE(i) + 0x98)
#define SPI_MEM_WAITI_DUMMY_CYCLELEN    0x0000003F
#define SPI_MEM_WAITI_DUMMY_CYCLELEN_M  ((SPI_MEM_WAITI_DUMMY_CYCLELEN_V)<<(SPI_MEM_WAITI_DUMMY_CYCLELEN_S))
#define SPI_MEM_WAITI_DUMMY_CYCLELEN_V  0x3F
#define SPI_MEM_WAITI_DUMMY_CYCLELEN_S  10
#define SPI_MEM_WAITI_CMD    0x000000FF
#define SPI_MEM_WAITI_CMD_M  ((SPI_MEM_WAITI_CMD_V)<<(SPI_MEM_WAITI_CMD_S))
#define SPI_MEM_WAITI_CMD_V  0xFF
#define SPI_MEM_WAITI_CMD_S  2
#define SPI_MEM_WAITI_DUMMY    (1<<(1))
#define SPI_MEM_WAITI_DUMMY_M  (1<<(1))
#define SPI_MEM_WAITI_DUMMY_V  0x1
#define SPI_MEM_WAITI_DUMMY_S  1
#define SPI_MEM_WAITI_EN    (1<<(0))
#define SPI_MEM_WAITI_EN_M  (1<<(0))
#define SPI_MEM_WAITI_EN_V  0x1
#define SPI_MEM_WAITI_EN_S  0
#define SPI_MEM_FLASH_SUS_CMD_REG(i)          (REG_SPI_MEM_BASE(i) + 0x9C)
#define SPI_MEM_PESR_IDLE_EN    (1<<(5))
#define SPI_MEM_PESR_IDLE_EN_M  (1<<(5))
#define SPI_MEM_PESR_IDLE_EN_V  0x1
#define SPI_MEM_PESR_IDLE_EN_S  5
#define SPI_MEM_PES_PER_EN    (1<<(4))
#define SPI_MEM_PES_PER_EN_M  (1<<(4))
#define SPI_MEM_PES_PER_EN_V  0x1
#define SPI_MEM_PES_PER_EN_S  4
#define SPI_MEM_FLASH_PES_WAIT_EN    (1<<(3))
#define SPI_MEM_FLASH_PES_WAIT_EN_M  (1<<(3))
#define SPI_MEM_FLASH_PES_WAIT_EN_V  0x1
#define SPI_MEM_FLASH_PES_WAIT_EN_S  3
#define SPI_MEM_FLASH_PER_WAIT_EN    (1<<(2))
#define SPI_MEM_FLASH_PER_WAIT_EN_M  (1<<(2))
#define SPI_MEM_FLASH_PER_WAIT_EN_V  0x1
#define SPI_MEM_FLASH_PER_WAIT_EN_S  2
#define SPI_MEM_FLASH_PES    (1<<(1))
#define SPI_MEM_FLASH_PES_M  (1<<(1))
#define SPI_MEM_FLASH_PES_V  0x1
#define SPI_MEM_FLASH_PES_S  1
#define SPI_MEM_FLASH_PER    (1<<(0))
#define SPI_MEM_FLASH_PER_M  (1<<(0))
#define SPI_MEM_FLASH_PER_V  0x1
#define SPI_MEM_FLASH_PER_S  0
#define SPI_MEM_FLASH_SUS_CTRL_REG(i)          (REG_SPI_MEM_BASE(i) + 0xA0)
#define SPI_MEM_FLASH_PES_COMMAND    0x000000FF
#define SPI_MEM_FLASH_PES_COMMAND_M  ((SPI_MEM_FLASH_PES_COMMAND_V)<<(SPI_MEM_FLASH_PES_COMMAND_S))
#define SPI_MEM_FLASH_PES_COMMAND_V  0xFF
#define SPI_MEM_FLASH_PES_COMMAND_S  9
#define SPI_MEM_FLASH_PER_COMMAND    0x000000FF
#define SPI_MEM_FLASH_PER_COMMAND_M  ((SPI_MEM_FLASH_PER_COMMAND_V)<<(SPI_MEM_FLASH_PER_COMMAND_S))
#define SPI_MEM_FLASH_PER_COMMAND_V  0xFF
#define SPI_MEM_FLASH_PER_COMMAND_S  1
#define SPI_MEM_FLASH_PES_EN    (1<<(0))
#define SPI_MEM_FLASH_PES_EN_M  (1<<(0))
#define SPI_MEM_FLASH_PES_EN_V  0x1
#define SPI_MEM_FLASH_PES_EN_S  0
#define SPI_MEM_SUS_STATUS_REG(i)          (REG_SPI_MEM_BASE(i) + 0xA4)
#define SPI_MEM_FLASH_PES_DLY_256    (1<<(6))
#define SPI_MEM_FLASH_PES_DLY_256_M  (1<<(6))
#define SPI_MEM_FLASH_PES_DLY_256_V  0x1
#define SPI_MEM_FLASH_PES_DLY_256_S  6
#define SPI_MEM_FLASH_PER_DLY_256    (1<<(5))
#define SPI_MEM_FLASH_PER_DLY_256_M  (1<<(5))
#define SPI_MEM_FLASH_PER_DLY_256_V  0x1
#define SPI_MEM_FLASH_PER_DLY_256_S  5
#define SPI_MEM_FLASH_DP_DLY_256    (1<<(4))
#define SPI_MEM_FLASH_DP_DLY_256_M  (1<<(4))
#define SPI_MEM_FLASH_DP_DLY_256_V  0x1
#define SPI_MEM_FLASH_DP_DLY_256_S  4
#define SPI_MEM_FLASH_RES_DLY_256    (1<<(3))
#define SPI_MEM_FLASH_RES_DLY_256_M  (1<<(3))
#define SPI_MEM_FLASH_RES_DLY_256_V  0x1
#define SPI_MEM_FLASH_RES_DLY_256_S  3
#define SPI_MEM_FLASH_HPM_DLY_256    (1<<(2))
#define SPI_MEM_FLASH_HPM_DLY_256_M  (1<<(2))
#define SPI_MEM_FLASH_HPM_DLY_256_V  0x1
#define SPI_MEM_FLASH_HPM_DLY_256_S  2
#define SPI_MEM_FLASH_SUS    (1<<(0))
#define SPI_MEM_FLASH_SUS_M  (1<<(0))
#define SPI_MEM_FLASH_SUS_V  0x1
#define SPI_MEM_FLASH_SUS_S  0
#define SPI_MEM_TIMING_CALI_REG(i)          (REG_SPI_MEM_BASE(i) + 0xA8)
#define SPI_MEM_EXTRA_DUMMY_CYCLELEN    0x00000007
#define SPI_MEM_EXTRA_DUMMY_CYCLELEN_M  ((SPI_MEM_EXTRA_DUMMY_CYCLELEN_V)<<(SPI_MEM_EXTRA_DUMMY_CYCLELEN_S))
#define SPI_MEM_EXTRA_DUMMY_CYCLELEN_V  0x7
#define SPI_MEM_EXTRA_DUMMY_CYCLELEN_S  2
#define SPI_MEM_TIMING_CALI    (1<<(1))
#define SPI_MEM_TIMING_CALI_M  (1<<(1))
#define SPI_MEM_TIMING_CALI_V  0x1
#define SPI_MEM_TIMING_CALI_S  1
#define SPI_MEM_TIMING_CLK_ENA    (1<<(0))
#define SPI_MEM_TIMING_CLK_ENA_M  (1<<(0))
#define SPI_MEM_TIMING_CLK_ENA_V  0x1
#define SPI_MEM_TIMING_CLK_ENA_S  0
#define SPI_MEM_DIN_MODE_REG(i)          (REG_SPI_MEM_BASE(i) + 0xAC)
#define SPI_MEM_DINS_MODE    0x00000007
#define SPI_MEM_DINS_MODE_M  ((SPI_MEM_DINS_MODE_V)<<(SPI_MEM_DINS_MODE_S))
#define SPI_MEM_DINS_MODE_V  0x7
#define SPI_MEM_DINS_MODE_S  24
#define SPI_MEM_DIN7_MODE    0x00000007
#define SPI_MEM_DIN7_MODE_M  ((SPI_MEM_DIN7_MODE_V)<<(SPI_MEM_DIN7_MODE_S))
#define SPI_MEM_DIN7_MODE_V  0x7
#define SPI_MEM_DIN7_MODE_S  21
#define SPI_MEM_DIN6_MODE    0x00000007
#define SPI_MEM_DIN6_MODE_M  ((SPI_MEM_DIN6_MODE_V)<<(SPI_MEM_DIN6_MODE_S))
#define SPI_MEM_DIN6_MODE_V  0x7
#define SPI_MEM_DIN6_MODE_S  18
#define SPI_MEM_DIN5_MODE    0x00000007
#define SPI_MEM_DIN5_MODE_M  ((SPI_MEM_DIN5_MODE_V)<<(SPI_MEM_DIN5_MODE_S))
#define SPI_MEM_DIN5_MODE_V  0x7
#define SPI_MEM_DIN5_MODE_S  15
#define SPI_MEM_DIN4_MODE    0x00000007
#define SPI_MEM_DIN4_MODE_M  ((SPI_MEM_DIN4_MODE_V)<<(SPI_MEM_DIN4_MODE_S))
#define SPI_MEM_DIN4_MODE_V  0x7
#define SPI_MEM_DIN4_MODE_S  12
#define SPI_MEM_DIN3_MODE    0x00000007
#define SPI_MEM_DIN3_MODE_M  ((SPI_MEM_DIN3_MODE_V)<<(SPI_MEM_DIN3_MODE_S))
#define SPI_MEM_DIN3_MODE_V  0x7
#define SPI_MEM_DIN3_MODE_S  9
#define SPI_MEM_DIN2_MODE    0x00000007
#define SPI_MEM_DIN2_MODE_M  ((SPI_MEM_DIN2_MODE_V)<<(SPI_MEM_DIN2_MODE_S))
#define SPI_MEM_DIN2_MODE_V  0x7
#define SPI_MEM_DIN2_MODE_S  6
#define SPI_MEM_DIN1_MODE    0x00000007
#define SPI_MEM_DIN1_MODE_M  ((SPI_MEM_DIN1_MODE_V)<<(SPI_MEM_DIN1_MODE_S))
#define SPI_MEM_DIN1_MODE_V  0x7
#define SPI_MEM_DIN1_MODE_S  3
#define SPI_MEM_DIN0_MODE    0x00000007
#define SPI_MEM_DIN0_MODE_M  ((SPI_MEM_DIN0_MODE_V)<<(SPI_MEM_DIN0_MODE_S))
#define SPI_MEM_DIN0_MODE_V  0x7
#define SPI_MEM_DIN0_MODE_S  0
#define SPI_MEM_DIN_NUM_REG(i)          (REG_SPI_MEM_BASE(i) + 0xB0)
#define SPI_MEM_DINS_NUM    0x00000003
#define SPI_MEM_DINS_NUM_M  ((SPI_MEM_DINS_NUM_V)<<(SPI_MEM_DINS_NUM_S))
#define SPI_MEM_DINS_NUM_V  0x3
#define SPI_MEM_DINS_NUM_S  16
#define SPI_MEM_DIN7_NUM    0x00000003
#define SPI_MEM_DIN7_NUM_M  ((SPI_MEM_DIN7_NUM_V)<<(SPI_MEM_DIN7_NUM_S))
#define SPI_MEM_DIN7_NUM_V  0x3
#define SPI_MEM_DIN7_NUM_S  14
#define SPI_MEM_DIN6_NUM    0x00000003
#define SPI_MEM_DIN6_NUM_M  ((SPI_MEM_DIN6_NUM_V)<<(SPI_MEM_DIN6_NUM_S))
#define SPI_MEM_DIN6_NUM_V  0x3
#define SPI_MEM_DIN6_NUM_S  12
#define SPI_MEM_DIN5_NUM    0x00000003
#define SPI_MEM_DIN5_NUM_M  ((SPI_MEM_DIN5_NUM_V)<<(SPI_MEM_DIN5_NUM_S))
#define SPI_MEM_DIN5_NUM_V  0x3
#define SPI_MEM_DIN5_NUM_S  10
#define SPI_MEM_DIN4_NUM    0x00000003
#define SPI_MEM_DIN4_NUM_M  ((SPI_MEM_DIN4_NUM_V)<<(SPI_MEM_DIN4_NUM_S))
#define SPI_MEM_DIN4_NUM_V  0x3
#define SPI_MEM_DIN4_NUM_S  8
#define SPI_MEM_DIN3_NUM    0x00000003
#define SPI_MEM_DIN3_NUM_M  ((SPI_MEM_DIN3_NUM_V)<<(SPI_MEM_DIN3_NUM_S))
#define SPI_MEM_DIN3_NUM_V  0x3
#define SPI_MEM_DIN3_NUM_S  6
#define SPI_MEM_DIN2_NUM    0x00000003
#define SPI_MEM_DIN2_NUM_M  ((SPI_MEM_DIN2_NUM_V)<<(SPI_MEM_DIN2_NUM_S))
#define SPI_MEM_DIN2_NUM_V  0x3
#define SPI_MEM_DIN2_NUM_S  4
#define SPI_MEM_DIN1_NUM    0x00000003
#define SPI_MEM_DIN1_NUM_M  ((SPI_MEM_DIN1_NUM_V)<<(SPI_MEM_DIN1_NUM_S))
#define SPI_MEM_DIN1_NUM_V  0x3
#define SPI_MEM_DIN1_NUM_S  2
#define SPI_MEM_DIN0_NUM    0x00000003
#define SPI_MEM_DIN0_NUM_M  ((SPI_MEM_DIN0_NUM_V)<<(SPI_MEM_DIN0_NUM_S))
#define SPI_MEM_DIN0_NUM_V  0x3
#define SPI_MEM_DIN0_NUM_S  0
#define SPI_MEM_DOUT_MODE_REG(i)          (REG_SPI_MEM_BASE(i) + 0xB4)
#define SPI_MEM_DOUTS_MODE    (1<<(8))
#define SPI_MEM_DOUTS_MODE_M  (1<<(8))
#define SPI_MEM_DOUTS_MODE_V  0x1
#define SPI_MEM_DOUTS_MODE_S  8
#define SPI_MEM_DOUT7_MODE    (1<<(7))
#define SPI_MEM_DOUT7_MODE_M  (1<<(7))
#define SPI_MEM_DOUT7_MODE_V  0x1
#define SPI_MEM_DOUT7_MODE_S  7
#define SPI_MEM_DOUT6_MODE    (1<<(6))
#define SPI_MEM_DOUT6_MODE_M  (1<<(6))
#define SPI_MEM_DOUT6_MODE_V  0x1
#define SPI_MEM_DOUT6_MODE_S  6
#define SPI_MEM_DOUT5_MODE    (1<<(5))
#define SPI_MEM_DOUT5_MODE_M  (1<<(5))
#define SPI_MEM_DOUT5_MODE_V  0x1
#define SPI_MEM_DOUT5_MODE_S  5
#define SPI_MEM_DOUT4_MODE    (1<<(4))
#define SPI_MEM_DOUT4_MODE_M  (1<<(4))
#define SPI_MEM_DOUT4_MODE_V  0x1
#define SPI_MEM_DOUT4_MODE_S  4
#define SPI_MEM_DOUT3_MODE    (1<<(3))
#define SPI_MEM_DOUT3_MODE_M  (1<<(3))
#define SPI_MEM_DOUT3_MODE_V  0x1
#define SPI_MEM_DOUT3_MODE_S  3
#define SPI_MEM_DOUT2_MODE    (1<<(2))
#define SPI_MEM_DOUT2_MODE_M  (1<<(2))
#define SPI_MEM_DOUT2_MODE_V  0x1
#define SPI_MEM_DOUT2_MODE_S  2
#define SPI_MEM_DOUT1_MODE    (1<<(1))
#define SPI_MEM_DOUT1_MODE_M  (1<<(1))
#define SPI_MEM_DOUT1_MODE_V  0x1
#define SPI_MEM_DOUT1_MODE_S  1
#define SPI_MEM_DOUT0_MODE    (1<<(0))
#define SPI_MEM_DOUT0_MODE_M  (1<<(0))
#define SPI_MEM_DOUT0_MODE_V  0x1
#define SPI_MEM_DOUT0_MODE_S  0
#define SPI_MEM_SPI_SMEM_TIMING_CALI_REG(i)          (REG_SPI_MEM_BASE(i) + 0xBC)
#define SPI_MEM_SPI_SMEM_EXTRA_DUMMY_CYCLELEN    0x00000007
#define SPI_MEM_SPI_SMEM_EXTRA_DUMMY_CYCLELEN_M  ((SPI_MEM_SPI_SMEM_EXTRA_DUMMY_CYCLELEN_V)<<(SPI_MEM_SPI_SMEM_EXTRA_DUMMY_CYCLELEN_S))
#define SPI_MEM_SPI_SMEM_EXTRA_DUMMY_CYCLELEN_V  0x7
#define SPI_MEM_SPI_SMEM_EXTRA_DUMMY_CYCLELEN_S  2
#define SPI_MEM_SPI_SMEM_TIMING_CALI    (1<<(1))
#define SPI_MEM_SPI_SMEM_TIMING_CALI_M  (1<<(1))
#define SPI_MEM_SPI_SMEM_TIMING_CALI_V  0x1
#define SPI_MEM_SPI_SMEM_TIMING_CALI_S  1
#define SPI_MEM_SPI_SMEM_TIMING_CLK_ENA    (1<<(0))
#define SPI_MEM_SPI_SMEM_TIMING_CLK_ENA_M  (1<<(0))
#define SPI_MEM_SPI_SMEM_TIMING_CLK_ENA_V  0x1
#define SPI_MEM_SPI_SMEM_TIMING_CLK_ENA_S  0
#define SPI_MEM_SPI_SMEM_DIN_MODE_REG(i)          (REG_SPI_MEM_BASE(i) + 0xC0)
#define SPI_MEM_SPI_SMEM_DINS_MODE    0x00000007
#define SPI_MEM_SPI_SMEM_DINS_MODE_M  ((SPI_MEM_SPI_SMEM_DINS_MODE_V)<<(SPI_MEM_SPI_SMEM_DINS_MODE_S))
#define SPI_MEM_SPI_SMEM_DINS_MODE_V  0x7
#define SPI_MEM_SPI_SMEM_DINS_MODE_S  24
#define SPI_MEM_SPI_SMEM_DIN7_MODE    0x00000007
#define SPI_MEM_SPI_SMEM_DIN7_MODE_M  ((SPI_MEM_SPI_SMEM_DIN7_MODE_V)<<(SPI_MEM_SPI_SMEM_DIN7_MODE_S))
#define SPI_MEM_SPI_SMEM_DIN7_MODE_V  0x7
#define SPI_MEM_SPI_SMEM_DIN7_MODE_S  21
#define SPI_MEM_SPI_SMEM_DIN6_MODE    0x00000007
#define SPI_MEM_SPI_SMEM_DIN6_MODE_M  ((SPI_MEM_SPI_SMEM_DIN6_MODE_V)<<(SPI_MEM_SPI_SMEM_DIN6_MODE_S))
#define SPI_MEM_SPI_SMEM_DIN6_MODE_V  0x7
#define SPI_MEM_SPI_SMEM_DIN6_MODE_S  18
#define SPI_MEM_SPI_SMEM_DIN5_MODE    0x00000007
#define SPI_MEM_SPI_SMEM_DIN5_MODE_M  ((SPI_MEM_SPI_SMEM_DIN5_MODE_V)<<(SPI_MEM_SPI_SMEM_DIN5_MODE_S))
#define SPI_MEM_SPI_SMEM_DIN5_MODE_V  0x7
#define SPI_MEM_SPI_SMEM_DIN5_MODE_S  15
#define SPI_MEM_SPI_SMEM_DIN4_MODE    0x00000007
#define SPI_MEM_SPI_SMEM_DIN4_MODE_M  ((SPI_MEM_SPI_SMEM_DIN4_MODE_V)<<(SPI_MEM_SPI_SMEM_DIN4_MODE_S))
#define SPI_MEM_SPI_SMEM_DIN4_MODE_V  0x7
#define SPI_MEM_SPI_SMEM_DIN4_MODE_S  12
#define SPI_MEM_SPI_SMEM_DIN3_MODE    0x00000007
#define SPI_MEM_SPI_SMEM_DIN3_MODE_M  ((SPI_MEM_SPI_SMEM_DIN3_MODE_V)<<(SPI_MEM_SPI_SMEM_DIN3_MODE_S))
#define SPI_MEM_SPI_SMEM_DIN3_MODE_V  0x7
#define SPI_MEM_SPI_SMEM_DIN3_MODE_S  9
#define SPI_MEM_SPI_SMEM_DIN2_MODE    0x00000007
#define SPI_MEM_SPI_SMEM_DIN2_MODE_M  ((SPI_MEM_SPI_SMEM_DIN2_MODE_V)<<(SPI_MEM_SPI_SMEM_DIN2_MODE_S))
#define SPI_MEM_SPI_SMEM_DIN2_MODE_V  0x7
#define SPI_MEM_SPI_SMEM_DIN2_MODE_S  6
#define SPI_MEM_SPI_SMEM_DIN1_MODE    0x00000007
#define SPI_MEM_SPI_SMEM_DIN1_MODE_M  ((SPI_MEM_SPI_SMEM_DIN1_MODE_V)<<(SPI_MEM_SPI_SMEM_DIN1_MODE_S))
#define SPI_MEM_SPI_SMEM_DIN1_MODE_V  0x7
#define SPI_MEM_SPI_SMEM_DIN1_MODE_S  3
#define SPI_MEM_SPI_SMEM_DIN0_MODE    0x00000007
#define SPI_MEM_SPI_SMEM_DIN0_MODE_M  ((SPI_MEM_SPI_SMEM_DIN0_MODE_V)<<(SPI_MEM_SPI_SMEM_DIN0_MODE_S))
#define SPI_MEM_SPI_SMEM_DIN0_MODE_V  0x7
#define SPI_MEM_SPI_SMEM_DIN0_MODE_S  0
#define SPI_MEM_SPI_SMEM_DIN_NUM_REG(i)          (REG_SPI_MEM_BASE(i) + 0xC4)
#define SPI_MEM_SPI_SMEM_DINS_NUM    0x00000003
#define SPI_MEM_SPI_SMEM_DINS_NUM_M  ((SPI_MEM_SPI_SMEM_DINS_NUM_V)<<(SPI_MEM_SPI_SMEM_DINS_NUM_S))
#define SPI_MEM_SPI_SMEM_DINS_NUM_V  0x3
#define SPI_MEM_SPI_SMEM_DINS_NUM_S  16
#define SPI_MEM_SPI_SMEM_DIN7_NUM    0x00000003
#define SPI_MEM_SPI_SMEM_DIN7_NUM_M  ((SPI_MEM_SPI_SMEM_DIN7_NUM_V)<<(SPI_MEM_SPI_SMEM_DIN7_NUM_S))
#define SPI_MEM_SPI_SMEM_DIN7_NUM_V  0x3
#define SPI_MEM_SPI_SMEM_DIN7_NUM_S  14
#define SPI_MEM_SPI_SMEM_DIN6_NUM    0x00000003
#define SPI_MEM_SPI_SMEM_DIN6_NUM_M  ((SPI_MEM_SPI_SMEM_DIN6_NUM_V)<<(SPI_MEM_SPI_SMEM_DIN6_NUM_S))
#define SPI_MEM_SPI_SMEM_DIN6_NUM_V  0x3
#define SPI_MEM_SPI_SMEM_DIN6_NUM_S  12
#define SPI_MEM_SPI_SMEM_DIN5_NUM    0x00000003
#define SPI_MEM_SPI_SMEM_DIN5_NUM_M  ((SPI_MEM_SPI_SMEM_DIN5_NUM_V)<<(SPI_MEM_SPI_SMEM_DIN5_NUM_S))
#define SPI_MEM_SPI_SMEM_DIN5_NUM_V  0x3
#define SPI_MEM_SPI_SMEM_DIN5_NUM_S  10
#define SPI_MEM_SPI_SMEM_DIN4_NUM    0x00000003
#define SPI_MEM_SPI_SMEM_DIN4_NUM_M  ((SPI_MEM_SPI_SMEM_DIN4_NUM_V)<<(SPI_MEM_SPI_SMEM_DIN4_NUM_S))
#define SPI_MEM_SPI_SMEM_DIN4_NUM_V  0x3
#define SPI_MEM_SPI_SMEM_DIN4_NUM_S  8
#define SPI_MEM_SPI_SMEM_DIN3_NUM    0x00000003
#define SPI_MEM_SPI_SMEM_DIN3_NUM_M  ((SPI_MEM_SPI_SMEM_DIN3_NUM_V)<<(SPI_MEM_SPI_SMEM_DIN3_NUM_S))
#define SPI_MEM_SPI_SMEM_DIN3_NUM_V  0x3
#define SPI_MEM_SPI_SMEM_DIN3_NUM_S  6
#define SPI_MEM_SPI_SMEM_DIN2_NUM    0x00000003
#define SPI_MEM_SPI_SMEM_DIN2_NUM_M  ((SPI_MEM_SPI_SMEM_DIN2_NUM_V)<<(SPI_MEM_SPI_SMEM_DIN2_NUM_S))
#define SPI_MEM_SPI_SMEM_DIN2_NUM_V  0x3
#define SPI_MEM_SPI_SMEM_DIN2_NUM_S  4
#define SPI_MEM_SPI_SMEM_DIN1_NUM    0x00000003
#define SPI_MEM_SPI_SMEM_DIN1_NUM_M  ((SPI_MEM_SPI_SMEM_DIN1_NUM_V)<<(SPI_MEM_SPI_SMEM_DIN1_NUM_S))
#define SPI_MEM_SPI_SMEM_DIN1_NUM_V  0x3
#define SPI_MEM_SPI_SMEM_DIN1_NUM_S  2
#define SPI_MEM_SPI_SMEM_DIN0_NUM    0x00000003
#define SPI_MEM_SPI_SMEM_DIN0_NUM_M  ((SPI_MEM_SPI_SMEM_DIN0_NUM_V)<<(SPI_MEM_SPI_SMEM_DIN0_NUM_S))
#define SPI_MEM_SPI_SMEM_DIN0_NUM_V  0x3
#define SPI_MEM_SPI_SMEM_DIN0_NUM_S  0
#define SPI_MEM_SPI_SMEM_DOUT_MODE_REG(i)          (REG_SPI_MEM_BASE(i) + 0xC8)
#define SPI_MEM_SPI_SMEM_DOUTS_MODE    (1<<(8))
#define SPI_MEM_SPI_SMEM_DOUTS_MODE_M  (1<<(8))
#define SPI_MEM_SPI_SMEM_DOUTS_MODE_V  0x1
#define SPI_MEM_SPI_SMEM_DOUTS_MODE_S  8
#define SPI_MEM_SPI_SMEM_DOUT7_MODE    (1<<(7))
#define SPI_MEM_SPI_SMEM_DOUT7_MODE_M  (1<<(7))
#define SPI_MEM_SPI_SMEM_DOUT7_MODE_V  0x1
#define SPI_MEM_SPI_SMEM_DOUT7_MODE_S  7
#define SPI_MEM_SPI_SMEM_DOUT6_MODE    (1<<(6))
#define SPI_MEM_SPI_SMEM_DOUT6_MODE_M  (1<<(6))
#define SPI_MEM_SPI_SMEM_DOUT6_MODE_V  0x1
#define SPI_MEM_SPI_SMEM_DOUT6_MODE_S  6
#define SPI_MEM_SPI_SMEM_DOUT5_MODE    (1<<(5))
#define SPI_MEM_SPI_SMEM_DOUT5_MODE_M  (1<<(5))
#define SPI_MEM_SPI_SMEM_DOUT5_MODE_V  0x1
#define SPI_MEM_SPI_SMEM_DOUT5_MODE_S  5
#define SPI_MEM_SPI_SMEM_DOUT4_MODE    (1<<(4))
#define SPI_MEM_SPI_SMEM_DOUT4_MODE_M  (1<<(4))
#define SPI_MEM_SPI_SMEM_DOUT4_MODE_V  0x1
#define SPI_MEM_SPI_SMEM_DOUT4_MODE_S  4
#define SPI_MEM_SPI_SMEM_DOUT3_MODE    (1<<(3))
#define SPI_MEM_SPI_SMEM_DOUT3_MODE_M  (1<<(3))
#define SPI_MEM_SPI_SMEM_DOUT3_MODE_V  0x1
#define SPI_MEM_SPI_SMEM_DOUT3_MODE_S  3
#define SPI_MEM_SPI_SMEM_DOUT2_MODE    (1<<(2))
#define SPI_MEM_SPI_SMEM_DOUT2_MODE_M  (1<<(2))
#define SPI_MEM_SPI_SMEM_DOUT2_MODE_V  0x1
#define SPI_MEM_SPI_SMEM_DOUT2_MODE_S  2
#define SPI_MEM_SPI_SMEM_DOUT1_MODE    (1<<(1))
#define SPI_MEM_SPI_SMEM_DOUT1_MODE_M  (1<<(1))
#define SPI_MEM_SPI_SMEM_DOUT1_MODE_V  0x1
#define SPI_MEM_SPI_SMEM_DOUT1_MODE_S  1
#define SPI_MEM_SPI_SMEM_DOUT0_MODE    (1<<(0))
#define SPI_MEM_SPI_SMEM_DOUT0_MODE_M  (1<<(0))
#define SPI_MEM_SPI_SMEM_DOUT0_MODE_V  0x1
#define SPI_MEM_SPI_SMEM_DOUT0_MODE_S  0
#define SPI_MEM_ECC_CTRL_REG(i)          (REG_SPI_MEM_BASE(i) + 0xCC)
#define SPI_MEM_SPI_FMEM_ECC_ERR_INT_EN    (1<<(8))
#define SPI_MEM_SPI_FMEM_ECC_ERR_INT_EN_M  (1<<(8))
#define SPI_MEM_SPI_FMEM_ECC_ERR_INT_EN_V  0x1
#define SPI_MEM_SPI_FMEM_ECC_ERR_INT_EN_S  8
#define SPI_MEM_ECC_ERR_INT_NUM    0x000000FF
#define SPI_MEM_ECC_ERR_INT_NUM_M  ((SPI_MEM_ECC_ERR_INT_NUM_V)<<(SPI_MEM_ECC_ERR_INT_NUM_S))
#define SPI_MEM_ECC_ERR_INT_NUM_V  0xFF
#define SPI_MEM_ECC_ERR_INT_NUM_S  0
#define SPI_MEM_ECC_ERR_ADDR_REG(i)          (REG_SPI_MEM_BASE(i) + 0xD0)
#define SPI_MEM_ECC_ERR_ADDR    0xFFFFFFFF
#define SPI_MEM_ECC_ERR_ADDR_M  ((SPI_MEM_ECC_ERR_ADDR_V)<<(SPI_MEM_ECC_ERR_ADDR_S))
#define SPI_MEM_ECC_ERR_ADDR_V  0xFFFFFFFF
#define SPI_MEM_ECC_ERR_ADDR_S  0
#define SPI_MEM_ECC_ERR_BIT_REG(i)          (REG_SPI_MEM_BASE(i) + 0xD4)
#define SPI_MEM_ECC_ERR_CNT    0x000000FF
#define SPI_MEM_ECC_ERR_CNT_M  ((SPI_MEM_ECC_ERR_CNT_V)<<(SPI_MEM_ECC_ERR_CNT_S))
#define SPI_MEM_ECC_ERR_CNT_V  0xFF
#define SPI_MEM_ECC_ERR_CNT_S  17
#define SPI_MEM_ECC_BYTE_ERR    (1<<(16))
#define SPI_MEM_ECC_BYTE_ERR_M  (1<<(16))
#define SPI_MEM_ECC_BYTE_ERR_V  0x1
#define SPI_MEM_ECC_BYTE_ERR_S  16
#define SPI_MEM_ECC_CHK_ERR_BIT    0x00000007
#define SPI_MEM_ECC_CHK_ERR_BIT_M  ((SPI_MEM_ECC_CHK_ERR_BIT_V)<<(SPI_MEM_ECC_CHK_ERR_BIT_S))
#define SPI_MEM_ECC_CHK_ERR_BIT_V  0x7
#define SPI_MEM_ECC_CHK_ERR_BIT_S  13
#define SPI_MEM_ECC_DATA_ERR_BIT    0x0000007F
#define SPI_MEM_ECC_DATA_ERR_BIT_M  ((SPI_MEM_ECC_DATA_ERR_BIT_V)<<(SPI_MEM_ECC_DATA_ERR_BIT_S))
#define SPI_MEM_ECC_DATA_ERR_BIT_V  0x7F
#define SPI_MEM_ECC_DATA_ERR_BIT_S  6
#define SPI_MEM_SPI_SMEM_AC_REG(i)          (REG_SPI_MEM_BASE(i) + 0xDC)
#define SPI_MEM_SPI_SMEM_CS_HOLD_DELAY    0x0000003F
#define SPI_MEM_SPI_SMEM_CS_HOLD_DELAY_M  ((SPI_MEM_SPI_SMEM_CS_HOLD_DELAY_V)<<(SPI_MEM_SPI_SMEM_CS_HOLD_DELAY_S))
#define SPI_MEM_SPI_SMEM_CS_HOLD_DELAY_V  0x3F
#define SPI_MEM_SPI_SMEM_CS_HOLD_DELAY_S  25
#define SPI_MEM_SPI_SMEM_ECC_ERR_INT_EN    (1<<(24))
#define SPI_MEM_SPI_SMEM_ECC_ERR_INT_EN_M  (1<<(24))
#define SPI_MEM_SPI_SMEM_ECC_ERR_INT_EN_V  0x1
#define SPI_MEM_SPI_SMEM_ECC_ERR_INT_EN_S  24
#define SPI_MEM_SPI_SMEM_ECC_16TO18_BYTE_EN    (1<<(16))
#define SPI_MEM_SPI_SMEM_ECC_16TO18_BYTE_EN_M  (1<<(16))
#define SPI_MEM_SPI_SMEM_ECC_16TO18_BYTE_EN_V  0x1
#define SPI_MEM_SPI_SMEM_ECC_16TO18_BYTE_EN_S  16
#define SPI_MEM_SPI_SMEM_ECC_SKIP_PAGE_CORNER    (1<<(15))
#define SPI_MEM_SPI_SMEM_ECC_SKIP_PAGE_CORNER_M  (1<<(15))
#define SPI_MEM_SPI_SMEM_ECC_SKIP_PAGE_CORNER_V  0x1
#define SPI_MEM_SPI_SMEM_ECC_SKIP_PAGE_CORNER_S  15
#define SPI_MEM_SPI_SMEM_ECC_CS_HOLD_TIME    0x00000007
#define SPI_MEM_SPI_SMEM_ECC_CS_HOLD_TIME_M  ((SPI_MEM_SPI_SMEM_ECC_CS_HOLD_TIME_V)<<(SPI_MEM_SPI_SMEM_ECC_CS_HOLD_TIME_S))
#define SPI_MEM_SPI_SMEM_ECC_CS_HOLD_TIME_V  0x7
#define SPI_MEM_SPI_SMEM_ECC_CS_HOLD_TIME_S  12
#define SPI_MEM_SPI_SMEM_CS_HOLD_TIME    0x0000001F
#define SPI_MEM_SPI_SMEM_CS_HOLD_TIME_M  ((SPI_MEM_SPI_SMEM_CS_HOLD_TIME_V)<<(SPI_MEM_SPI_SMEM_CS_HOLD_TIME_S))
#define SPI_MEM_SPI_SMEM_CS_HOLD_TIME_V  0x1F
#define SPI_MEM_SPI_SMEM_CS_HOLD_TIME_S  7
#define SPI_MEM_SPI_SMEM_CS_SETUP_TIME    0x0000001F
#define SPI_MEM_SPI_SMEM_CS_SETUP_TIME_M  ((SPI_MEM_SPI_SMEM_CS_SETUP_TIME_V)<<(SPI_MEM_SPI_SMEM_CS_SETUP_TIME_S))
#define SPI_MEM_SPI_SMEM_CS_SETUP_TIME_V  0x1F
#define SPI_MEM_SPI_SMEM_CS_SETUP_TIME_S  2
#define SPI_MEM_SPI_SMEM_CS_HOLD    (1<<(1))
#define SPI_MEM_SPI_SMEM_CS_HOLD_M  (1<<(1))
#define SPI_MEM_SPI_SMEM_CS_HOLD_V  0x1
#define SPI_MEM_SPI_SMEM_CS_HOLD_S  1
#define SPI_MEM_SPI_SMEM_CS_SETUP    (1<<(0))
#define SPI_MEM_SPI_SMEM_CS_SETUP_M  (1<<(0))
#define SPI_MEM_SPI_SMEM_CS_SETUP_V  0x1
#define SPI_MEM_SPI_SMEM_CS_SETUP_S  0
#define SPI_MEM_DDR_REG(i)          (REG_SPI_MEM_BASE(i) + 0xE0)
#define SPI_MEM_SPI_FMEM_HYPERBUS_CA    (1<<(30))
#define SPI_MEM_SPI_FMEM_HYPERBUS_CA_M  (1<<(30))
#define SPI_MEM_SPI_FMEM_HYPERBUS_CA_V  0x1
#define SPI_MEM_SPI_FMEM_HYPERBUS_CA_S  30
#define SPI_MEM_SPI_FMEM_OCTA_RAM_ADDR    (1<<(29))
#define SPI_MEM_SPI_FMEM_OCTA_RAM_ADDR_M  (1<<(29))
#define SPI_MEM_SPI_FMEM_OCTA_RAM_ADDR_V  0x1
#define SPI_MEM_SPI_FMEM_OCTA_RAM_ADDR_S  29
#define SPI_MEM_SPI_FMEM_CLK_DIFF_INV    (1<<(28))
#define SPI_MEM_SPI_FMEM_CLK_DIFF_INV_M  (1<<(28))
#define SPI_MEM_SPI_FMEM_CLK_DIFF_INV_V  0x1
#define SPI_MEM_SPI_FMEM_CLK_DIFF_INV_S  28
#define SPI_MEM_SPI_FMEM_HYPERBUS_DUMMY_2X    (1<<(27))
#define SPI_MEM_SPI_FMEM_HYPERBUS_DUMMY_2X_M  (1<<(27))
#define SPI_MEM_SPI_FMEM_HYPERBUS_DUMMY_2X_V  0x1
#define SPI_MEM_SPI_FMEM_HYPERBUS_DUMMY_2X_S  27
#define SPI_MEM_SPI_FMEM_DQS_CA_IN    (1<<(26))
#define SPI_MEM_SPI_FMEM_DQS_CA_IN_M  (1<<(26))
#define SPI_MEM_SPI_FMEM_DQS_CA_IN_V  0x1
#define SPI_MEM_SPI_FMEM_DQS_CA_IN_S  26
#define SPI_MEM_SPI_FMEM_HYPERBUS_MODE    (1<<(25))
#define SPI_MEM_SPI_FMEM_HYPERBUS_MODE_M  (1<<(25))
#define SPI_MEM_SPI_FMEM_HYPERBUS_MODE_V  0x1
#define SPI_MEM_SPI_FMEM_HYPERBUS_MODE_S  25
#define SPI_MEM_SPI_FMEM_CLK_DIFF_EN    (1<<(24))
#define SPI_MEM_SPI_FMEM_CLK_DIFF_EN_M  (1<<(24))
#define SPI_MEM_SPI_FMEM_CLK_DIFF_EN_V  0x1
#define SPI_MEM_SPI_FMEM_CLK_DIFF_EN_S  24
#define SPI_MEM_SPI_FMEM_DDR_DQS_LOOP_MODE    (1<<(22))
#define SPI_MEM_SPI_FMEM_DDR_DQS_LOOP_MODE_M  (1<<(22))
#define SPI_MEM_SPI_FMEM_DDR_DQS_LOOP_MODE_V  0x1
#define SPI_MEM_SPI_FMEM_DDR_DQS_LOOP_MODE_S  22
#define SPI_MEM_SPI_FMEM_DDR_DQS_LOOP    (1<<(21))
#define SPI_MEM_SPI_FMEM_DDR_DQS_LOOP_M  (1<<(21))
#define SPI_MEM_SPI_FMEM_DDR_DQS_LOOP_V  0x1
#define SPI_MEM_SPI_FMEM_DDR_DQS_LOOP_S  21
#define SPI_MEM_SPI_FMEM_USR_DDR_DQS_THD    0x0000007F
#define SPI_MEM_SPI_FMEM_USR_DDR_DQS_THD_M  ((SPI_MEM_SPI_FMEM_USR_DDR_DQS_THD_V)<<(SPI_MEM_SPI_FMEM_USR_DDR_DQS_THD_S))
#define SPI_MEM_SPI_FMEM_USR_DDR_DQS_THD_V  0x7F
#define SPI_MEM_SPI_FMEM_USR_DDR_DQS_THD_S  14
#define SPI_MEM_SPI_FMEM_RX_DDR_MSK_EN    (1<<(13))
#define SPI_MEM_SPI_FMEM_RX_DDR_MSK_EN_M  (1<<(13))
#define SPI_MEM_SPI_FMEM_RX_DDR_MSK_EN_V  0x1
#define SPI_MEM_SPI_FMEM_RX_DDR_MSK_EN_S  13
#define SPI_MEM_SPI_FMEM_TX_DDR_MSK_EN    (1<<(12))
#define SPI_MEM_SPI_FMEM_TX_DDR_MSK_EN_M  (1<<(12))
#define SPI_MEM_SPI_FMEM_TX_DDR_MSK_EN_V  0x1
#define SPI_MEM_SPI_FMEM_TX_DDR_MSK_EN_S  12
#define SPI_MEM_SPI_FMEM_OUTMINBYTELEN    0x0000007F
#define SPI_MEM_SPI_FMEM_OUTMINBYTELEN_M  ((SPI_MEM_SPI_FMEM_OUTMINBYTELEN_V)<<(SPI_MEM_SPI_FMEM_OUTMINBYTELEN_S))
#define SPI_MEM_SPI_FMEM_OUTMINBYTELEN_V  0x7F
#define SPI_MEM_SPI_FMEM_OUTMINBYTELEN_S  5
#define SPI_MEM_SPI_FMEM_DDR_CMD_DIS    (1<<(4))
#define SPI_MEM_SPI_FMEM_DDR_CMD_DIS_M  (1<<(4))
#define SPI_MEM_SPI_FMEM_DDR_CMD_DIS_V  0x1
#define SPI_MEM_SPI_FMEM_DDR_CMD_DIS_S  4
#define SPI_MEM_SPI_FMEM_DDR_WDAT_SWP    (1<<(3))
#define SPI_MEM_SPI_FMEM_DDR_WDAT_SWP_M  (1<<(3))
#define SPI_MEM_SPI_FMEM_DDR_WDAT_SWP_V  0x1
#define SPI_MEM_SPI_FMEM_DDR_WDAT_SWP_S  3
#define SPI_MEM_SPI_FMEM_DDR_RDAT_SWP    (1<<(2))
#define SPI_MEM_SPI_FMEM_DDR_RDAT_SWP_M  (1<<(2))
#define SPI_MEM_SPI_FMEM_DDR_RDAT_SWP_V  0x1
#define SPI_MEM_SPI_FMEM_DDR_RDAT_SWP_S  2
#define SPI_MEM_SPI_FMEM_VAR_DUMMY    (1<<(1))
#define SPI_MEM_SPI_FMEM_VAR_DUMMY_M  (1<<(1))
#define SPI_MEM_SPI_FMEM_VAR_DUMMY_V  0x1
#define SPI_MEM_SPI_FMEM_VAR_DUMMY_S  1
#define SPI_MEM_SPI_FMEM_DDR_EN    (1<<(0))
#define SPI_MEM_SPI_FMEM_DDR_EN_M  (1<<(0))
#define SPI_MEM_SPI_FMEM_DDR_EN_V  0x1
#define SPI_MEM_SPI_FMEM_DDR_EN_S  0
#define SPI_MEM_SPI_SMEM_DDR_REG(i)          (REG_SPI_MEM_BASE(i) + 0xE4)
#define SPI_MEM_SPI_SMEM_HYPERBUS_CA    (1<<(30))
#define SPI_MEM_SPI_SMEM_HYPERBUS_CA_M  (1<<(30))
#define SPI_MEM_SPI_SMEM_HYPERBUS_CA_V  0x1
#define SPI_MEM_SPI_SMEM_HYPERBUS_CA_S  30
#define SPI_MEM_SPI_SMEM_OCTA_RAM_ADDR    (1<<(29))
#define SPI_MEM_SPI_SMEM_OCTA_RAM_ADDR_M  (1<<(29))
#define SPI_MEM_SPI_SMEM_OCTA_RAM_ADDR_V  0x1
#define SPI_MEM_SPI_SMEM_OCTA_RAM_ADDR_S  29
#define SPI_MEM_SPI_SMEM_CLK_DIFF_INV    (1<<(28))
#define SPI_MEM_SPI_SMEM_CLK_DIFF_INV_M  (1<<(28))
#define SPI_MEM_SPI_SMEM_CLK_DIFF_INV_V  0x1
#define SPI_MEM_SPI_SMEM_CLK_DIFF_INV_S  28
#define SPI_MEM_SPI_SMEM_HYPERBUS_DUMMY_2X    (1<<(27))
#define SPI_MEM_SPI_SMEM_HYPERBUS_DUMMY_2X_M  (1<<(27))
#define SPI_MEM_SPI_SMEM_HYPERBUS_DUMMY_2X_V  0x1
#define SPI_MEM_SPI_SMEM_HYPERBUS_DUMMY_2X_S  27
#define SPI_MEM_SPI_SMEM_DQS_CA_IN    (1<<(26))
#define SPI_MEM_SPI_SMEM_DQS_CA_IN_M  (1<<(26))
#define SPI_MEM_SPI_SMEM_DQS_CA_IN_V  0x1
#define SPI_MEM_SPI_SMEM_DQS_CA_IN_S  26
#define SPI_MEM_SPI_SMEM_HYPERBUS_MODE    (1<<(25))
#define SPI_MEM_SPI_SMEM_HYPERBUS_MODE_M  (1<<(25))
#define SPI_MEM_SPI_SMEM_HYPERBUS_MODE_V  0x1
#define SPI_MEM_SPI_SMEM_HYPERBUS_MODE_S  25
#define SPI_MEM_SPI_SMEM_CLK_DIFF_EN    (1<<(24))
#define SPI_MEM_SPI_SMEM_CLK_DIFF_EN_M  (1<<(24))
#define SPI_MEM_SPI_SMEM_CLK_DIFF_EN_V  0x1
#define SPI_MEM_SPI_SMEM_CLK_DIFF_EN_S  24
#define SPI_MEM_SPI_SMEM_DDR_DQS_LOOP_MODE    (1<<(22))
#define SPI_MEM_SPI_SMEM_DDR_DQS_LOOP_MODE_M  (1<<(22))
#define SPI_MEM_SPI_SMEM_DDR_DQS_LOOP_MODE_V  0x1
#define SPI_MEM_SPI_SMEM_DDR_DQS_LOOP_MODE_S  22
#define SPI_MEM_SPI_SMEM_DDR_DQS_LOOP    (1<<(21))
#define SPI_MEM_SPI_SMEM_DDR_DQS_LOOP_M  (1<<(21))
#define SPI_MEM_SPI_SMEM_DDR_DQS_LOOP_V  0x1
#define SPI_MEM_SPI_SMEM_DDR_DQS_LOOP_S  21
#define SPI_MEM_SPI_SMEM_USR_DDR_DQS_THD    0x0000007F
#define SPI_MEM_SPI_SMEM_USR_DDR_DQS_THD_M  ((SPI_MEM_SPI_SMEM_USR_DDR_DQS_THD_V)<<(SPI_MEM_SPI_SMEM_USR_DDR_DQS_THD_S))
#define SPI_MEM_SPI_SMEM_USR_DDR_DQS_THD_V  0x7F
#define SPI_MEM_SPI_SMEM_USR_DDR_DQS_THD_S  14
#define SPI_MEM_SPI_SMEM_RX_DDR_MSK_EN    (1<<(13))
#define SPI_MEM_SPI_SMEM_RX_DDR_MSK_EN_M  (1<<(13))
#define SPI_MEM_SPI_SMEM_RX_DDR_MSK_EN_V  0x1
#define SPI_MEM_SPI_SMEM_RX_DDR_MSK_EN_S  13
#define SPI_MEM_SPI_SMEM_TX_DDR_MSK_EN    (1<<(12))
#define SPI_MEM_SPI_SMEM_TX_DDR_MSK_EN_M  (1<<(12))
#define SPI_MEM_SPI_SMEM_TX_DDR_MSK_EN_V  0x1
#define SPI_MEM_SPI_SMEM_TX_DDR_MSK_EN_S  12
#define SPI_MEM_SPI_SMEM_OUTMINBYTELEN    0x0000007F
#define SPI_MEM_SPI_SMEM_OUTMINBYTELEN_M  ((SPI_MEM_SPI_SMEM_OUTMINBYTELEN_V)<<(SPI_MEM_SPI_SMEM_OUTMINBYTELEN_S))
#define SPI_MEM_SPI_SMEM_OUTMINBYTELEN_V  0x7F
#define SPI_MEM_SPI_SMEM_OUTMINBYTELEN_S  5
#define SPI_MEM_SPI_SMEM_DDR_CMD_DIS    (1<<(4))
#define SPI_MEM_SPI_SMEM_DDR_CMD_DIS_M  (1<<(4))
#define SPI_MEM_SPI_SMEM_DDR_CMD_DIS_V  0x1
#define SPI_MEM_SPI_SMEM_DDR_CMD_DIS_S  4
#define SPI_MEM_SPI_SMEM_DDR_WDAT_SWP    (1<<(3))
#define SPI_MEM_SPI_SMEM_DDR_WDAT_SWP_M  (1<<(3))
#define SPI_MEM_SPI_SMEM_DDR_WDAT_SWP_V  0x1
#define SPI_MEM_SPI_SMEM_DDR_WDAT_SWP_S  3
#define SPI_MEM_SPI_SMEM_DDR_RDAT_SWP    (1<<(2))
#define SPI_MEM_SPI_SMEM_DDR_RDAT_SWP_M  (1<<(2))
#define SPI_MEM_SPI_SMEM_DDR_RDAT_SWP_V  0x1
#define SPI_MEM_SPI_SMEM_DDR_RDAT_SWP_S  2
#define SPI_MEM_SPI_SMEM_VAR_DUMMY    (1<<(1))
#define SPI_MEM_SPI_SMEM_VAR_DUMMY_M  (1<<(1))
#define SPI_MEM_SPI_SMEM_VAR_DUMMY_V  0x1
#define SPI_MEM_SPI_SMEM_VAR_DUMMY_S  1
#define SPI_MEM_SPI_SMEM_DDR_EN    (1<<(0))
#define SPI_MEM_SPI_SMEM_DDR_EN_M  (1<<(0))
#define SPI_MEM_SPI_SMEM_DDR_EN_V  0x1
#define SPI_MEM_SPI_SMEM_DDR_EN_S  0
#define SPI_MEM_CLOCK_GATE_REG(i)          (REG_SPI_MEM_BASE(i) + 0xE8)
#define SPI_MEM_CLK_EN    (1<<(0))
#define SPI_MEM_CLK_EN_M  (1<<(0))
#define SPI_MEM_CLK_EN_V  0x1
#define SPI_MEM_CLK_EN_S  0
#define SPI_MEM_CORE_CLK_SEL_REG(i)          (REG_SPI_MEM_BASE(i) + 0xEC)
#define SPI_MEM_CORE_CLK_SEL    0x00000003
#define SPI_MEM_CORE_CLK_SEL_M  ((SPI_MEM_CORE_CLK_SEL_V)<<(SPI_MEM_CORE_CLK_SEL_S))
#define SPI_MEM_CORE_CLK_SEL_V  0x3
#define SPI_MEM_CORE_CLK_SEL_S  0
#define SPI_MEM_INT_ENA_REG(i)          (REG_SPI_MEM_BASE(i) + 0xF0)
#define SPI_MEM_ECC_ERR_INT_ENA    (1<<(4))
#define SPI_MEM_ECC_ERR_INT_ENA_M  (1<<(4))
#define SPI_MEM_ECC_ERR_INT_ENA_V  0x1
#define SPI_MEM_ECC_ERR_INT_ENA_S  4
#define SPI_MEM_BROWN_OUT_INT_ENA    (1<<(3))
#define SPI_MEM_BROWN_OUT_INT_ENA_M  (1<<(3))
#define SPI_MEM_BROWN_OUT_INT_ENA_V  0x1
#define SPI_MEM_BROWN_OUT_INT_ENA_S  3
#define SPI_MEM_TOTAL_TRANS_END_INT_ENA    (1<<(2))
#define SPI_MEM_TOTAL_TRANS_END_INT_ENA_M  (1<<(2))
#define SPI_MEM_TOTAL_TRANS_END_INT_ENA_V  0x1
#define SPI_MEM_TOTAL_TRANS_END_INT_ENA_S  2
#define SPI_MEM_PES_END_INT_ENA    (1<<(1))
#define SPI_MEM_PES_END_INT_ENA_M  (1<<(1))
#define SPI_MEM_PES_END_INT_ENA_V  0x1
#define SPI_MEM_PES_END_INT_ENA_S  1
#define SPI_MEM_PER_END_INT_ENA    (1<<(0))
#define SPI_MEM_PER_END_INT_ENA_M  (1<<(0))
#define SPI_MEM_PER_END_INT_ENA_V  0x1
#define SPI_MEM_PER_END_INT_ENA_S  0
#define SPI_MEM_INT_CLR_REG(i)          (REG_SPI_MEM_BASE(i) + 0xF4)
#define SPI_MEM_ECC_ERR_INT_CLR    (1<<(4))
#define SPI_MEM_ECC_ERR_INT_CLR_M  (1<<(4))
#define SPI_MEM_ECC_ERR_INT_CLR_V  0x1
#define SPI_MEM_ECC_ERR_INT_CLR_S  4
#define SPI_MEM_BROWN_OUT_INT_CLR    (1<<(3))
#define SPI_MEM_BROWN_OUT_INT_CLR_M  (1<<(3))
#define SPI_MEM_BROWN_OUT_INT_CLR_V  0x1
#define SPI_MEM_BROWN_OUT_INT_CLR_S  3
#define SPI_MEM_TOTAL_TRANS_END_INT_CLR    (1<<(2))
#define SPI_MEM_TOTAL_TRANS_END_INT_CLR_M  (1<<(2))
#define SPI_MEM_TOTAL_TRANS_END_INT_CLR_V  0x1
#define SPI_MEM_TOTAL_TRANS_END_INT_CLR_S  2
#define SPI_MEM_PES_END_INT_CLR    (1<<(1))
#define SPI_MEM_PES_END_INT_CLR_M  (1<<(1))
#define SPI_MEM_PES_END_INT_CLR_V  0x1
#define SPI_MEM_PES_END_INT_CLR_S  1
#define SPI_MEM_PER_END_INT_CLR    (1<<(0))
#define SPI_MEM_PER_END_INT_CLR_M  (1<<(0))
#define SPI_MEM_PER_END_INT_CLR_V  0x1
#define SPI_MEM_PER_END_INT_CLR_S  0
#define SPI_MEM_INT_RAW_REG(i)          (REG_SPI_MEM_BASE(i) + 0xF8)
#define SPI_MEM_ECC_ERR_INT_RAW    (1<<(4))
#define SPI_MEM_ECC_ERR_INT_RAW_M  (1<<(4))
#define SPI_MEM_ECC_ERR_INT_RAW_V  0x1
#define SPI_MEM_ECC_ERR_INT_RAW_S  4
#define SPI_MEM_BROWN_OUT_INT_RAW    (1<<(3))
#define SPI_MEM_BROWN_OUT_INT_RAW_M  (1<<(3))
#define SPI_MEM_BROWN_OUT_INT_RAW_V  0x1
#define SPI_MEM_BROWN_OUT_INT_RAW_S  3
#define SPI_MEM_TOTAL_TRANS_END_INT_RAW    (1<<(2))
#define SPI_MEM_TOTAL_TRANS_END_INT_RAW_M  (1<<(2))
#define SPI_MEM_TOTAL_TRANS_END_INT_RAW_V  0x1
#define SPI_MEM_TOTAL_TRANS_END_INT_RAW_S  2
#define SPI_MEM_PES_END_INT_RAW    (1<<(1))
#define SPI_MEM_PES_END_INT_RAW_M  (1<<(1))
#define SPI_MEM_PES_END_INT_RAW_V  0x1
#define SPI_MEM_PES_END_INT_RAW_S  1
#define SPI_MEM_PER_END_INT_RAW    (1<<(0))
#define SPI_MEM_PER_END_INT_RAW_M  (1<<(0))
#define SPI_MEM_PER_END_INT_RAW_V  0x1
#define SPI_MEM_PER_END_INT_RAW_S  0
#define SPI_MEM_INT_ST_REG(i)          (REG_SPI_MEM_BASE(i) + 0xFC)
#define SPI_MEM_ECC_ERR_INT_ST    (1<<(4))
#define SPI_MEM_ECC_ERR_INT_ST_M  (1<<(4))
#define SPI_MEM_ECC_ERR_INT_ST_V  0x1
#define SPI_MEM_ECC_ERR_INT_ST_S  4
#define SPI_MEM_BROWN_OUT_INT_ST    (1<<(3))
#define SPI_MEM_BROWN_OUT_INT_ST_M  (1<<(3))
#define SPI_MEM_BROWN_OUT_INT_ST_V  0x1
#define SPI_MEM_BROWN_OUT_INT_ST_S  3
#define SPI_MEM_TOTAL_TRANS_END_INT_ST    (1<<(2))
#define SPI_MEM_TOTAL_TRANS_END_INT_ST_M  (1<<(2))
#define SPI_MEM_TOTAL_TRANS_END_INT_ST_V  0x1
#define SPI_MEM_TOTAL_TRANS_END_INT_ST_S  2
#define SPI_MEM_PES_END_INT_ST    (1<<(1))
#define SPI_MEM_PES_END_INT_ST_M  (1<<(1))
#define SPI_MEM_PES_END_INT_ST_V  0x1
#define SPI_MEM_PES_END_INT_ST_S  1
#define SPI_MEM_PER_END_INT_ST    (1<<(0))
#define SPI_MEM_PER_END_INT_ST_M  (1<<(0))
#define SPI_MEM_PER_END_INT_ST_V  0x1
#define SPI_MEM_PER_END_INT_ST_S  0
#define SPI_MEM_DATE_REG(i)          (REG_SPI_MEM_BASE(i) + 0x3FC)
#define SPI_MEM_DATE    0x007FFFFF
#define SPI_MEM_DATE_M  ((SPI_MEM_DATE_V)<<(SPI_MEM_DATE_S))
#define SPI_MEM_DATE_V  0x7FFFFF
#define SPI_MEM_DATE_S  5
#define SPI_MEM_SPICLK_PAD_DRV_CTL_EN    (1<<(4))
#define SPI_MEM_SPICLK_PAD_DRV_CTL_EN_M  (1<<(4))
#define SPI_MEM_SPICLK_PAD_DRV_CTL_EN_V  0x1
#define SPI_MEM_SPICLK_PAD_DRV_CTL_EN_S  4
#define SPI_MEM_SPI_FMEM_SPICLK_FUN_DRV    0x00000003
#define SPI_MEM_SPI_FMEM_SPICLK_FUN_DRV_M  ((SPI_MEM_SPI_FMEM_SPICLK_FUN_DRV_V)<<(SPI_MEM_SPI_FMEM_SPICLK_FUN_DRV_S))
#define SPI_MEM_SPI_FMEM_SPICLK_FUN_DRV_V  0x3
#define SPI_MEM_SPI_FMEM_SPICLK_FUN_DRV_S  2
#define SPI_MEM_SPI_SMEM_SPICLK_FUN_DRV    0x00000003
#define SPI_MEM_SPI_SMEM_SPICLK_FUN_DRV_M  ((SPI_MEM_SPI_SMEM_SPICLK_FUN_DRV_V)<<(SPI_MEM_SPI_SMEM_SPICLK_FUN_DRV_S))
#define SPI_MEM_SPI_SMEM_SPICLK_FUN_DRV_V  0x3
#define SPI_MEM_SPI_SMEM_SPICLK_FUN_DRV_S  0

#define OPI_PSRAM_SYNC_READ             0x0000
#define OPI_PSRAM_SYNC_WRITE            0x8080
#define OPI_PSRAM_REG_READ              0x4040
#define OPI_PSRAM_REG_WRITE             0xC0C0
#define OCT_PSRAM_RD_CMD_BITLEN         16
#define OCT_PSRAM_WR_CMD_BITLEN         16
#define OCT_PSRAM_ADDR_BITLEN           32
#define OCT_PSRAM_RD_DUMMY_BITLEN       (2*(10-1))
#define OCT_PSRAM_WR_DUMMY_BITLEN       (2*(5-1))
#define OCT_PSRAM_CS1_IO                SPI_CS1_GPIO_NUM
#define OCT_PSRAM_CS_SETUP_TIME         3
#define OCT_PSRAM_CS_HOLD_TIME          3
#define OCT_PSRAM_CS_HOLD_DELAY         2

typedef enum {
	PSRAM_CACHE_S80M = 1,
	PSRAM_CACHE_S40M,
	PSRAM_CACHE_MAX,
} psram_cache_mode_t;

typedef enum {
	PSRAM_VADDR_MODE_NORMAL=0, ///< App and pro CPU use their own flash cache for external RAM access
	PSRAM_VADDR_MODE_LOWHIGH,  ///< App and pro CPU share external RAM caches: pro CPU has low 2M, app CPU has high 2M
	PSRAM_VADDR_MODE_EVENODD,  ///< App and pro CPU share external RAM caches: pro CPU does even 32yte ranges, app does odd ones.
} psram_vaddr_mode_t;


typedef struct {
	union {
		struct {
			uint8_t drive_str: 2;
			uint8_t read_latency: 3;
			uint8_t lt: 1;
			uint8_t rsvd0_1: 2;
		};
		uint8_t val;
	} mr0;
	union {
		struct {
			uint8_t vendor_id: 5;
			uint8_t rsvd0_2: 3;
		};
		uint8_t val;
	} mr1;
	union {
		struct {
			uint8_t density: 3;
			uint8_t dev_id: 2;
			uint8_t rsvd1_2: 2;
			uint8_t gb: 1;
		};
		uint8_t val;
	} mr2;
	union {
		struct {
			uint8_t rsvd3_7: 5;
			uint8_t srf: 1;
			uint8_t vcc: 1;
			uint8_t rsvd0: 1;
		};
		uint8_t val;
	} mr3;
	union {
		struct {
			uint8_t pasr: 3;
			uint8_t rf: 1;
			uint8_t rsvd3: 1;
			uint8_t wr_latency: 3;
		};
		uint8_t val;
	} mr4;
	union {
		struct {
			uint8_t bl: 2;
			uint8_t bt: 1;
			uint8_t rsvd0_4: 5;
		};
		uint8_t val;
	} mr8;
} opi_psram_mode_reg_t;


#if CONFIG_SPIRAM_SPEED_40M
#define PSRAM_SPEED PSRAM_CACHE_S40M
#else  //#if CONFIG_SPIRAM_SPEED_80M
#define PSRAM_SPEED PSRAM_CACHE_S80M
#endif

bool esp_spiram_is_initialized(void);
bool esp_spiram_test(void);
int esp_spiram_add_to_heapalloc(void);
int esp_spiram_enable_instruction_access(void);
int esp_spiram_enable_rodata_access(void);
int esp_spiram_init(void);
int esp_spiram_reserve_dma_pool(size_t size);
int instruction_flash2spiram_offset(void);
int rodata_flash2spiram_offset(void);
size_t esp_spiram_get_size(void);
uint32_t esp_spiram_instruction_access_enabled(void);
uint32_t esp_spiram_rodata_access_enabled(void);
uint32_t instruction_flash_end_page_get(void);
uint32_t instruction_flash_start_page_get(void);
uint32_t rodata_flash_end_page_get(void);
uint32_t rodata_flash_start_page_get(void);
uint8_t esp_spiram_get_cs_io(void);
void esp_spiram_init_cache(void);
void esp_spiram_writeback_cache(void);
void instruction_flash_page_info_init(void);
void rodata_flash_page_info_init(void);
